package com.punchh.server.apiConfig;

public class KafkaPayloads {

	// payload is related to automationtwentythree business only , we can
	// parameterised business_slug / business_uuid / business_id later
	// event_name = users
	public String getGuestCreationPayload(String email, String user_id) {
		email = "autoiframe130642050520252g80qwrrrr@punchh.com" ;
		user_id = "130642" ;
		String payload = "{\"content_id\":\"1cf7d9d0-941b-4b76-a30e-63bce8a2shgf\",\"timestamp\":1745947446,\"business_id\":2022,\"business_uuid\":\"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\"business_slug\":\"automationtwentythree\",\"event_name\":\"users\",\"event_type\":\"\",\"action\":\"create\",\"payload\":{\"account_balance\":{\"net_balance\":0,\"net_debits\":0,\"total_lifetime_points\":0,\"total_point_credits\":0,\"total_redeemable_visits\":0,\"unredeemed_cards\":0,\"user_id\":"
				+ user_id
				+ "},\"birthday\":\"1966-04-04\",\"business_id\":2022,\"created_at\":\"2025-04-29T22:54:06+05:30\",\"current_sign_in_at\":\"2025-04-29T22:54:06+05:30\",\"current_sign_in_ip\":\"127.0.0.1\",\"email\":\""
				+ email + "\",\"external_source\":\"\",\"external_source_id\":\"" + user_id
				+ "\",\"fav_locations\":[],\"favourite_store_numbers\":\"\",\"first_name\":\"shashankFname"+user_id+"\",\"gender\":\"Male\",\"guest_type\":\"Loyalty\",\"joined_at\":\"2025-04-29T22:54:06+05:30\",\"last_activity_at\":\"2025-04-29T22:54:06+05:30\",\"last_name\":\"SharmaLName"+user_id+"\",\"last_sign_in_at\":\"2025-04-29T22:54:06+05:30\",\"last_sign_in_ip\":\"127.0.0.1\",\"marketing_email_subscription\":true,\"marketing_pn_subscription\":true,\"previous_changes\":[\"id\",\"email\",\"encrypted_password\",\"current_sign_in_at\",\"last_sign_in_at\",\"current_sign_in_ip\",\"last_sign_in_ip\",\"first_name\",\"last_name\",\"authentication_token\",\"joined_at\",\"created_at\",\"updated_at\",\"gender\",\"birthday\",\"signup_channel\",\"referral_code\",\"time_zone\",\"user_details\",\"zip_code\",\"subscription_status\",\"business_id\",\"last_activity_at\"],\"profile_fields\":[],\"referral_code\":\"TestFce7996\",\"signup_channel\":\"MobileEmail\",\"sms_subscription\":false,\"terms_and_conditions\":false,\"time_zone\":\"Asia/Kolkata\",\"unsubscribed\":false,\"updated_at\":\"2025-04-29T22:54:06+05:30\",\"user_external_identifiers\":[],\"user_id\":"
				+ user_id + ",\"user_relations\":[],\"user_status\":\"active\",\"zip_code\":\"110015\"}}";

		return payload.toString() ;
	}
	
	
	public String getCreateUserOnKafkaPayload(String email, String user_id) {
		String payload = "{\n"
				+ "	\"content_id\": \"d24e0ba9-106c-4f55-bcee-"+user_id+"\",\n"
				+ "	\"timestamp\": 1731399223,\n"
				+ "	\"business_id\": 2022,\n"
				+ "	\"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "	\"business_slug\": \"automationtwentythree\",\n"
				+ "	\"event_name\": \"users\",\n"
				+ "	\"event_type\": \"\",\n"
				+ "	\"action\": \"create\",\n"
				+ "	\"payload\": {\n"
				+ "		\"account_balance\": {\n"
				+ "			\"current_membership_level_name\": \"Silver Level\",\n"
				+ "			\"loyalty_points\": 0,\n"
				+ "			\"net_balance\": 2,\n"
				+ "			\"net_debits\": 0,\n"
				+ "			\"pending_points\": 0,\n"
				+ "			\"total_credits\": 2,\n"
				+ "			\"total_debits\": \"0.0\",\n"
				+ "			\"total_lifetime_points\": 2,\n"
				+ "			\"total_point_credits\": 2,\n"
				+ "			\"total_visits\": 0,\n"
				+ "			\"user_id\": 169692\n"
				+ "		},\n"
				+ "		\"business_id\": 2022,\n"
				+ "		\"confirmation_sent_at\": \"2024-11-12T08:13:34Z\",\n"
				+ "		\"created_at\": \"2024-11-12T08:13:33Z\",\n"
				+ "		\"current_sign_in_at\": \"2024-11-12T08:13:33Z\",\n"
				+ "		\"current_sign_in_ip\": \"10.78.24.0\",\n"
				+ "		\"email\": \""+email+"\",\n"
				+ "		\"external_source\": \"\",\n"
				+ "		\"external_source_id\": \"169692\",\n"
				+ "		\"fav_locations\": [],\n"
				+ "		\"favourite_store_numbers\": \"\",\n"
				+ "		\"first_name\": \"Rohit5may-022\",\n"
				+ "		\"guest_type\": \"Loyalty\",\n"
				+ "		\"joined_at\": \"2024-11-12T08:13:33Z\",\n"
				+ "		\"last_activity_at\": \"2024-11-12T08:13:33Z\",\n"
				+ "		\"last_name\": \"Bsr3542\",\n"
				+ "		\"last_sign_in_at\": \"2024-11-12T08:13:33Z\",\n"
				+ "		\"last_sign_in_ip\": \"10.78.24.0\",\n"
				+ "		\"last_user_agent\": \"MyRewards/2.0/2 (x86_64; iOS 10.3; Scale/2.00)\",\n"
				+ "		\"marketing_email_subscription\": true,\n"
				+ "		\"marketing_pn_subscription\": true,\n"
				+ "		\"previous_changes\": [\n"
				+ "			\"id\",\n"
				+ "			\"email\",\n"
				+ "			\"encrypted_password\",\n"
				+ "			\"current_sign_in_at\",\n"
				+ "			\"last_sign_in_at\",\n"
				+ "			\"current_sign_in_ip\",\n"
				+ "			\"last_sign_in_ip\",\n"
				+ "			\"first_name\",\n"
				+ "			\"last_name\",\n"
				+ "			\"authentication_token\",\n"
				+ "			\"joined_at\",\n"
				+ "			\"created_at\",\n"
				+ "			\"updated_at\",\n"
				+ "			\"signup_channel\",\n"
				+ "			\"referral_code\",\n"
				+ "			\"subscription_status\",\n"
				+ "			\"business_id\",\n"
				+ "			\"last_activity_at\"\n"
				+ "		],\n"
				+ "		\"profile_fields\": [],\n"
				+ "		\"referral_code\": \"Rohi82Bs8080\",\n"
				+ "		\"signup_channel\": \"MobileEmail\",\n"
				+ "		\"sms_subscription\": false,\n"
				+ "		\"terms_and_conditions\": false,\n"
				+ "		\"unsubscribed\": false,\n"
				+ "		\"updated_at\": \"2024-11-12T08:13:37Z\",\n"
				+ "		\"user_external_identifiers\": [],\n"
				+ "		\"user_id\": 169692,\n"
				+ "		\"user_relations\": [],\n"
				+ "		\"user_status\": \"active\"\n"
				+ "	}\n"
				+ "}";
		
		return payload.toString() ;
	}
	
	public String createRewardEventPayload(String email, String user_id) {
		String payload ="{\n"
				+ "  \"content_id\": \"411c7b83-2975-464d-9256-"+user_id+"\",\n"
				+ "  \"timestamp\": 1746445414,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"rewards\",\n"
				+ "  \"event_type\": \"\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"payload\": {\n"
				+ "    \"becomes_available_at\": \"2025-05-05T04:43:17-07:00\",\n"
				+ "    \"campaign_id\": null,\n"
				+ "    \"campaign_name\": null,\n"
				+ "    \"campaign_type\": null,\n"
				+ "    \"created_at\": \"2025-05-05T11:43:17Z\",\n"
				+ "    \"description\": null,\n"
				+ "    \"discount_amount\": 0,\n"
				+ "    \"discount_channel\": null,\n"
				+ "    \"expiring_at\": null,\n"
				+ "    \"expiring_at_tz\": null,\n"
				+ "    \"external_campaign_id\": null,\n"
				+ "    \"franchisee_id\": null,\n"
				+ "    \"gift_reason\": \"Guest Relations\",\n"
				+ "    \"gifted_for_id\": 121408685,\n"
				+ "    \"gifted_for_type\": \"FeedbackReply\",\n"
				+ "    \"meta_data\": null,\n"
				+ "    \"name\": \"Base Redeemable\",\n"
				+ "    \"read_at\": null,\n"
				+ "    \"redeemable_created_at\": \"2025-04-28T12:43:08Z\",\n"
				+ "    \"redeemable_id\": 2827738,\n"
				+ "    \"redemption_id\": null,\n"
				+ "    \"reward_id\": 14235241963,\n"
				+ "    \"reward_image_url\": \"https://res.cloudinary.com/punchh/image/upload/fl_lossy,q_auto/v1/static/punchh-icon-thumb.png\",\n"
				+ "    \"reward_points_redeemed\": 0,\n"
				+ "    \"reward_properties\": null,\n"
				+ "    \"status\": \"unredeemed\",\n"
				+ "    \"store_numbers\": [],\n"
				+ "    \"updated_at\": \"2025-05-05T11:43:17Z\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": null,\n"
				+ "        \"loyalty_points\": null,\n"
				+ "        \"net_balance\": 0,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": null,\n"
				+ "        \"total_credits\": null,\n"
				+ "        \"total_debits\": null,\n"
				+ "        \"total_lifetime_points\": 0,\n"
				+ "        \"total_point_credits\": 0,\n"
				+ "        \"total_redeemable_visits\": 0,\n"
				+ "        \"total_visits\": null,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 0,\n"
				+ "        \"user_id\": 455368548\n"
				+ "      },\n"
				+ "      \"anniversary\": null,\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": \"1966-04-04\",\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"455368548\",\n"
				+ "      \"first_name\": \"TestFName"+user_id+"\",\n"
				+ "      \"gender\": \"Male\",\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-02T08:59:22Z\",\n"
				+ "      \"last_name\": \"TestLName"+user_id+"\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": "+user_id+",\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    }\n"
				+ "  }\n"
				+ "}";
		
		
		return payload ; 
		
	}
	
	public String getLoayltyCheckinEventPayload(String email, String user_id) {
		String payload ="{\n"
				+ "  \"content_id\": \"be4de1b5-c00f-4fb5-9b36-"+user_id+"\",\n"
				+ "  \"timestamp\": 1746061775,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"f06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"checkins\",\n"
				+ "  \"event_type\": \"loyalty\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"payload\": {\n"
				+ "    \"approved\": true,\n"
				+ "    \"bar_code\": \"0000448526681\",\n"
				+ "    \"campaign_id\": null,\n"
				+ "    \"campaign_name\": null,\n"
				+ "    \"campaign_type\": null,\n"
				+ "    \"channel\": \"POS\",\n"
				+ "    \"checkin_id\": 21754183722,\n"
				+ "    \"checkin_type\": \"PosCheckin\",\n"
				+ "    \"created_at\": \"2025-05-01T01:09:14Z\",\n"
				+ "    \"earnable_amount\": 20.79,\n"
				+ "    \"expired_at\": null,\n"
				+ "    \"expiring_on\": null,\n"
				+ "    \"external_uid\": null,\n"
				+ "    \"first_punchh_at_business\": true,\n"
				+ "    \"first_punchh_at_location\": true,\n"
				+ "    \"for_referring_checkin_id\": null,\n"
				+ "    \"for_referring_full_name\": null,\n"
				+ "    \"for_referring_user_id\": null,\n"
				+ "    \"free_punchh_campaign_id\": null,\n"
				+ "    \"gift_reason\": null,\n"
				+ "    \"gifted_by_id\": null,\n"
				+ "    \"gifted_by_type\": null,\n"
				+ "    \"gifted_for_id\": null,\n"
				+ "    \"gifted_for_type\": null,\n"
				+ "    \"location_id\": 408326,\n"
				+ "    \"location_name\": \"AutomationLocation\",\n"
				+ "    \"manual\": null,\n"
				+ "    \"menu_items\": [\n"
				+ "      {\n"
				+ "        \"item_amount\": 7.95,\n"
				+ "        \"item_name\": \"TestMenuItemCola\",\n"
				+ "        \"item_qty\": 3,\n"
				+ "        \"menu_family\": \"752\",\n"
				+ "        \"menu_item_id\": \"9364\",\n"
				+ "        \"menu_item_type\": \"S\",\n"
				+ "        \"menu_major_group\": \"223\",\n"
				+ "        \"serial_number\": \"1\"\n"
				+ "      },\n"
				+ "      {\n"
				+ "        \"item_amount\": 7.49,\n"
				+ "        \"item_name\": \"TestMenuItemCola\",\n"
				+ "        \"item_qty\": 3,\n"
				+ "        \"menu_family\": \"466\",\n"
				+ "        \"menu_item_id\": \"9364\",\n"
				+ "        \"menu_item_type\": \"S\",\n"
				+ "        \"menu_major_group\": \"813\",\n"
				+ "        \"serial_number\": \"2\"\n"
				+ "      },\n"
				+ "      {\n"
				+ "        \"item_amount\": 5.35,\n"
				+ "        \"item_name\": \"TestMenuItemCola\",\n"
				+ "        \"item_qty\": 3,\n"
				+ "        \"menu_family\": \"494\",\n"
				+ "        \"menu_item_id\": \"9364\",\n"
				+ "        \"menu_item_type\": \"S\",\n"
				+ "        \"menu_major_group\": \"536\",\n"
				+ "        \"serial_number\": \"3\"\n"
				+ "      }\n"
				+ "    ],\n"
				+ "    \"pending_refresh\": false,\n"
				+ "    \"points_earned\": 1,\n"
				+ "    \"points_spent\": 0,\n"
				+ "    \"punchh_key\": \"00044852668\",\n"
				+ "    \"qr_decoded\": null,\n"
				+ "    \"receipt_amount\": 20.79,\n"
				+ "    \"receipt_date\": \"2025-05-01T18:35:17Z\",\n"
				+ "    \"redemption_id\": 0,\n"
				+ "    \"refreshed_at\": null,\n"
				+ "    \"revenue_code\": \"\",\n"
				+ "    \"revenue_id\": \"\",\n"
				+ "    \"reviewer_id\": null,\n"
				+ "    \"status\": \"loyalty\",\n"
				+ "    \"store_number\": \"01\",\n"
				+ "    \"transaction_no\": \"3412\",\n"
				+ "    \"unverified_receipt_amount\": null,\n"
				+ "    \"updated_at\": \"2025-05-01T01:09:14Z\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": \"2025-05-01T01:09:14Z\",\n"
				+ "        \"loyalty_points\": 1,\n"
				+ "        \"net_balance\": 1,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": 0,\n"
				+ "        \"total_credits\": 1,\n"
				+ "        \"total_debits\": \"0.0\",\n"
				+ "        \"total_lifetime_points\": 1,\n"
				+ "        \"total_point_credits\": 1,\n"
				+ "        \"total_redeemable_visits\": 1,\n"
				+ "        \"total_visits\": 1,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 0,\n"
				+ "        \"user_id\": "+user_id+"\n"
				+ "      },\n"
				+ "      \"anniversary\": null,\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": \"1966-04-04\",\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \""+user_id+"\",\n"
				+ "      \"first_name\": \"TestFName"+user_id+"\",\n"
				+ "      \"gender\": null,\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-01T01:09:14Z\",\n"
				+ "      \"last_name\": \"TestLName"+user_id+"\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": "+user_id+",\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    },\n"
				+ "    \"user_id\": "+user_id+",\n"
				+ "    \"verifications_count\": null,\n"
				+ "    \"verified_at\": null\n"
				+ "  }\n"
				+ "}";
		return payload ;
	}
	
	public String getLoyaltyRedemptionEventPayload(String email, String user_id) {
		String payload ="{\n"
				+ "  \"content_id\": \"aaf3f017-483a-44fb-b888-"+user_id+"\",\n"
				+ "  \"timestamp\": 1746062331,\n"
				+ "  \"business_id\": 685,\n"
				+ "  \"business_uuid\": \"f06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"redemptions\",\n"
				+ "  \"event_type\": \"\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"payload\": {\n"
				+ "    \"additional_properties\": \"{\\\"revenue_code\\\":\\\"\\\",\\\"revenue_id\\\":\\\"\\\"}\",\n"
				+ "    \"admin_id\": null,\n"
				+ "    \"bar_code\": \"01184501052025\",\n"
				+ "    \"channel\": \"POS\",\n"
				+ "    \"created_at\": \"2025-05-01T01:18:45Z\",\n"
				+ "    \"expired_at\": null,\n"
				+ "    \"expiring_on\": \"2025-05-01T02:48:45Z\",\n"
				+ "    \"force_message\": null,\n"
				+ "    \"internal_tracking_code\": \"6367663\",\n"
				+ "    \"location_id\": 338762,\n"
				+ "    \"location_name\": \"Adelanto (14200 Highway 395)\",\n"
				+ "    \"points_requested\": 13,\n"
				+ "    \"redeemable_id\": 2826766,\n"
				+ "    \"redeemable_name\": \"DoNotDeleteUsedForWebhook_automation\",\n"
				+ "    \"redeemable_properties\": null,\n"
				+ "    \"redeemed_points\": 10,\n"
				+ "    \"redemption_code\": {\n"
				+ "      \"business_id\": 685,\n"
				+ "      \"business_uuid\": \"f9ed1a8a-91e8-45f2-b818-4646e009d67e\",\n"
				+ "      \"created_at\": \"2025-04-25T12:51:31Z\",\n"
				+ "      \"discount\": 13,\n"
				+ "      \"employee_id\": null,\n"
				+ "      \"location_id\": 338762,\n"
				+ "      \"processed_at\": \"2025-05-01T01:18:45Z\",\n"
				+ "      \"receipt_amount\": 10,\n"
				+ "      \"receipt_datetime\": \"2025-05-01 10:57:32 -0700\",\n"
				+ "      \"redeemable_id\": 2826766,\n"
				+ "      \"redeemed_menu_items\": [\n"
				+ "        {\n"
				+ "          \"item_amount\": 10,\n"
				+ "          \"item_name\": \"Philly Cheesesteak Omelette\",\n"
				+ "          \"item_qty\": 1,\n"
				+ "          \"menu_family\": \"106\",\n"
				+ "          \"menu_item_id\": \"123\",\n"
				+ "          \"menu_item_type\": \"M\",\n"
				+ "          \"menu_major_group\": \"100\",\n"
				+ "          \"serial_number\": \"1.0\"\n"
				+ "        }\n"
				+ "      ],\n"
				+ "      \"redemption_code_id\": 493351987,\n"
				+ "      \"revenue_code\": \"\",\n"
				+ "      \"revenue_id\": \"\",\n"
				+ "      \"status\": \"processed\",\n"
				+ "      \"subtotal_amount\": 10,\n"
				+ "      \"transaction_no\": \"12345601184501052025\",\n"
				+ "      \"updated_at\": \"2025-05-01T01:18:45Z\"\n"
				+ "    },\n"
				+ "    \"redemption_code_id\": 493351987,\n"
				+ "    \"redemption_code_pass\": null,\n"
				+ "    \"redemption_id\": 519315955,\n"
				+ "    \"redemption_status\": \"redeemed\",\n"
				+ "    \"redemption_type\": \"RewardRedemption\",\n"
				+ "    \"reward_id\": 14235189062,\n"
				+ "    \"store_number\": \"1000\",\n"
				+ "    \"transferred_to_id\": null,\n"
				+ "    \"transferred_to_type\": null,\n"
				+ "    \"updated_at\": \"2025-05-01T01:18:45Z\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": null,\n"
				+ "        \"loyalty_points\": 0,\n"
				+ "        \"net_balance\": 200,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": 0,\n"
				+ "        \"total_credits\": 200,\n"
				+ "        \"total_debits\": \"0.0\",\n"
				+ "        \"total_lifetime_points\": 200,\n"
				+ "        \"total_point_credits\": 200,\n"
				+ "        \"total_redeemable_visits\": 200,\n"
				+ "        \"total_visits\": 0,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 33,\n"
				+ "        \"user_id\": 455367659\n"
				+ "      },\n"
				+ "      \"anniversary\": null,\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": \"1966-04-04\",\n"
				+ "      \"email\": \"autoiframe01183801052025oavm2n@punchh.com\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"455367659\",\n"
				+ "      \"first_name\": \"TestFName01183801052025\",\n"
				+ "      \"gender\": \"Male\",\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-01T01:18:45Z\",\n"
				+ "      \"last_name\": \"TestLName01183801052025\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": 455367659,\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    },\n"
				+ "    \"user_id\": 455367659,\n"
				+ "    \"web\": null\n"
				+ "  }\n"
				+ "}";
		return payload ;
	}
	
	public String getPayload(String email) {
String payload = "{\n"
		+ "  \"content_id\": \"be5f014a-2f51-408a-abf1-75666bc82444\",\n"
		+ "  \"timestamp\": 1746532961,\n"
		+ "  \"business_id\": 2022,\n"
		+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
		+ "  \"business_slug\": \"automationtwentythree\",\n"
		+ "  \"event_name\": \"checkins\",\n"
		+ "  \"event_type\": \"loyalty\",\n"
		+ "  \"action\": \"create\",\n"
		+ "  \"kafka_offset\": 2613578,\n"
		+ "  \"kafka_partition\": 1,\n"
		+ "  \"is_rate_limit\": false,\n"
		+ "  \"payload\": {\n"
		+ "    \"approved\": true,\n"
		+ "    \"bar_code\": \"17321506052025\",\n"
		+ "    \"campaign_id\": null,\n"
		+ "    \"campaign_name\": null,\n"
		+ "    \"campaign_type\": null,\n"
		+ "    \"channel\": \"POS\",\n"
		+ "    \"checkin_id\": 21757099949,\n"
		+ "    \"checkin_type\": \"PosCheckin\",\n"
		+ "    \"created_at\": \"2025-05-06T12:02:17Z\",\n"
		+ "    \"earnable_amount\": 50,\n"
		+ "    \"expired_at\": null,\n"
		+ "    \"expiring_on\": null,\n"
		+ "    \"external_uid\": \"17321506052025\",\n"
		+ "    \"first_punchh_at_business\": true,\n"
		+ "    \"first_punchh_at_location\": true,\n"
		+ "    \"for_referring_checkin_id\": null,\n"
		+ "    \"for_referring_full_name\": null,\n"
		+ "    \"for_referring_user_id\": null,\n"
		+ "    \"free_punchh_campaign_id\": null,\n"
		+ "    \"gift_reason\": null,\n"
		+ "    \"gifted_by_id\": null,\n"
		+ "    \"gifted_by_type\": null,\n"
		+ "    \"gifted_for_id\": null,\n"
		+ "    \"gifted_for_type\": null,\n"
		+ "    \"location_id\": 408326,\n"
		+ "    \"location_name\": \"AutomationLocation\",\n"
		+ "    \"manual\": null,\n"
		+ "    \"menu_items\": [\n"
		+ "      {\n"
		+ "        \"item_amount\": 100,\n"
		+ "        \"item_name\": \"Margherita\",\n"
		+ "        \"item_qty\": 1,\n"
		+ "        \"menu_family\": \"106\",\n"
		+ "        \"menu_item_id\": \"110\",\n"
		+ "        \"menu_item_type\": \"M\",\n"
		+ "        \"menu_major_group\": \"100\",\n"
		+ "        \"serial_number\": \"1.0\"\n"
		+ "      },\n"
		+ "      {\n"
		+ "        \"item_amount\": 110,\n"
		+ "        \"item_name\": \"Pizza\",\n"
		+ "        \"item_qty\": 1,\n"
		+ "        \"menu_family\": \"106\",\n"
		+ "        \"menu_item_id\": \"111\",\n"
		+ "        \"menu_item_type\": \"M\",\n"
		+ "        \"menu_major_group\": \"100\",\n"
		+ "        \"serial_number\": \"1.0\"\n"
		+ "      }\n"
		+ "    ],\n"
		+ "    \"pending_refresh\": false,\n"
		+ "    \"points_earned\": 1,\n"
		+ "    \"points_spent\": 0,\n"
		+ "    \"punchh_key\": \"73215060520\",\n"
		+ "    \"qr_decoded\": null,\n"
		+ "    \"receipt_amount\": 50,\n"
		+ "    \"receipt_date\": null,\n"
		+ "    \"redemption_id\": 0,\n"
		+ "    \"refreshed_at\": null,\n"
		+ "    \"revenue_code\": null,\n"
		+ "    \"revenue_id\": null,\n"
		+ "    \"reviewer_id\": null,\n"
		+ "    \"status\": \"loyalty\",\n"
		+ "    \"store_number\": \"01\",\n"
		+ "    \"transaction_no\": \"1234565445717321506052025\",\n"
		+ "    \"unverified_receipt_amount\": null,\n"
		+ "    \"updated_at\": \"2025-05-06T12:02:17Z\",\n"
		+ "    \"user\": {\n"
		+ "      \"account_balance\": {\n"
		+ "        \"banked_currency\": null,\n"
		+ "        \"current_membership_level_name\": null,\n"
		+ "        \"last_visit\": \"2025-05-06T12:02:17Z\",\n"
		+ "        \"loyalty_points\": 1,\n"
		+ "        \"net_balance\": 1,\n"
		+ "        \"net_debits\": 0,\n"
		+ "        \"pending_points\": 0,\n"
		+ "        \"total_credits\": 1,\n"
		+ "        \"total_debits\": \"0.0\",\n"
		+ "        \"total_lifetime_points\": 1,\n"
		+ "        \"total_point_credits\": 1,\n"
		+ "        \"total_redeemable_visits\": 1,\n"
		+ "        \"total_visits\": 1,\n"
		+ "        \"unbanked_points\": null,\n"
		+ "        \"unredeemed_cards\": 0,\n"
		+ "        \"user_id\": 455369971\n"
		+ "      },\n"
		+ "      \"anniversary\": null,\n"
		+ "      \"avatar_remote_url\": null,\n"
		+ "      \"birthday\": \"1966-04-04\",\n"
		+ "      \"email\": \""+email+"\",\n"
		+ "      \"external_source\": \"\",\n"
		+ "      \"external_source_id\": \"455369971\",\n"
		+ "      \"first_name\": \"TestFName17321106052025\",\n"
		+ "      \"gender\": null,\n"
		+ "      \"guest_type\": \"Loyalty\",\n"
		+ "      \"last_activity_at\": \"2025-05-06T12:02:17Z\",\n"
		+ "      \"last_name\": \"TestLName17321106052025\",\n"
		+ "      \"marketing_email_subscription\": true,\n"
		+ "      \"marketing_pn_subscription\": true,\n"
		+ "      \"phone\": null,\n"
		+ "      \"preferred_locale\": null,\n"
		+ "      \"secondary_email\": null,\n"
		+ "      \"signup_channel\": \"MobileEmail\",\n"
		+ "      \"sms_subscription\": false,\n"
		+ "      \"unsubscribe_reason\": null,\n"
		+ "      \"unsubscribed\": false,\n"
		+ "      \"user_id\": 455369971,\n"
		+ "      \"user_status\": \"active\"\n"
		+ "    },\n"
		+ "    \"user_id\": 455369971,\n"
		+ "    \"verifications_count\": null,\n"
		+ "    \"verified_at\": null\n"
		+ "  }\n"
		+ "}";
		return payload ;
	}
	
	//\"event_type\": \"confirmation_email
	public String getTransactionalPayload(String email) {
		String payload = "{\n"
				+ "  \"content_id\": \"7a278ed7-757b-420c-b8cc-d0195ece00b8\",\n"
				+ "  \"timestamp\": 1746170427,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"transactional_notifications\",\n"
				+ "  \"event_type\": \"confirmation_email\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"payload\": {\n"
				+ "    \"account_balance\": {\n"
				+ "      \"banked_currency\": null,\n"
				+ "      \"current_membership_level_name\": null,\n"
				+ "      \"last_visit\": null,\n"
				+ "      \"loyalty_points\": null,\n"
				+ "      \"net_balance\": 0,\n"
				+ "      \"net_debits\": 0,\n"
				+ "      \"pending_points\": null,\n"
				+ "      \"total_credits\": null,\n"
				+ "      \"total_debits\": null,\n"
				+ "      \"total_lifetime_points\": 0,\n"
				+ "      \"total_point_credits\": 0,\n"
				+ "      \"total_redeemable_visits\": 0,\n"
				+ "      \"total_visits\": null,\n"
				+ "      \"unbanked_points\": null,\n"
				+ "      \"unredeemed_cards\": 0,\n"
				+ "      \"user_id\": 455368542\n"
				+ "    },\n"
				+ "    \"anniversary\": null,\n"
				+ "    \"avatar_remote_url\": null,\n"
				+ "    \"birthday\": \"1966-04-04\",\n"
				+ "    \"email\": \""+email+"\",\n"
				+ "    \"email_confirmation_url\": \"https://dashboard.punchh.com/customers/confirmation.iframe?confirmation_token=sxyrRQojpxbEmLonD9o2&slug=deltaco\",\n"
				+ "    \"external_source\": \"\",\n"
				+ "    \"external_source_id\": \"455368542\",\n"
				+ "    \"first_name\": \"TestFName07202702052025\",\n"
				+ "    \"gender\": null,\n"
				+ "    \"guest_type\": \"Loyalty\",\n"
				+ "    \"last_activity_at\": \"2025-05-02T07:20:27Z\",\n"
				+ "    \"last_name\": \"TestLName07202702052025\",\n"
				+ "    \"marketing_email_subscription\": true,\n"
				+ "    \"marketing_pn_subscription\": true,\n"
				+ "    \"phone\": null,\n"
				+ "    \"preferred_locale\": null,\n"
				+ "    \"reset_password_url\": null,\n"
				+ "    \"secondary_email\": null,\n"
				+ "    \"signup_channel\": \"MobileEmail\",\n"
				+ "    \"sms_subscription\": false,\n"
				+ "    \"unsubscribe_reason\": null,\n"
				+ "    \"unsubscribed\": false,\n"
				+ "    \"user_id\": 455368542,\n"
				+ "    \"user_status\": \"active\"\n"
				+ "  }\n"
				+ "}";
		return payload ;
		
	}
	
	
	public String getRedemptionEventPayload(String email) {
		String payload = "{\n"
				+ "  \"content_id\": \"794593dd-aa77-4e3d-80fc-29519903726e\",\n"
				+ "  \"timestamp\": 1746170255,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"redemptions\",\n"
				+ "  \"event_type\": \"\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"payload\": {\n"
				+ "    \"additional_properties\": \"{\\\"revenue_code\\\":\\\"\\\",\\\"revenue_id\\\":\\\"\\\"}\",\n"
				+ "    \"admin_id\": null,\n"
				+ "    \"bar_code\": \"07172902052025\",\n"
				+ "    \"channel\": \"POS\",\n"
				+ "    \"created_at\": \"2025-05-02T07:17:30Z\",\n"
				+ "    \"expired_at\": null,\n"
				+ "    \"expiring_on\": \"2025-05-02T08:47:30Z\",\n"
				+ "    \"force_message\": null,\n"
				+ "    \"internal_tracking_code\": \"6556227\",\n"
				+ "    \"location_id\": 338762,\n"
				+ "    \"location_name\": \"Adelanto (14200 Highway 395)\",\n"
				+ "    \"points_requested\": 13,\n"
				+ "    \"redeemable_id\": 2826766,\n"
				+ "    \"redeemable_name\": \"DoNotDeleteUsedForWebhook_automation\",\n"
				+ "    \"redeemable_properties\": null,\n"
				+ "    \"redeemed_points\": 10,\n"
				+ "    \"redemption_code\": {\n"
				+ "      \"business_id\": 685,\n"
				+ "      \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "      \"created_at\": \"2025-04-25T12:51:32Z\",\n"
				+ "      \"discount\": 13,\n"
				+ "      \"employee_id\": null,\n"
				+ "      \"location_id\": 338762,\n"
				+ "      \"processed_at\": \"2025-05-02T07:17:30Z\",\n"
				+ "      \"receipt_amount\": 10,\n"
				+ "      \"receipt_datetime\": \"2025-05-02 10:57:32 -0700\",\n"
				+ "      \"redeemable_id\": 2826766,\n"
				+ "      \"redeemed_menu_items\": [\n"
				+ "        {\n"
				+ "          \"item_amount\": 10,\n"
				+ "          \"item_name\": \"Philly Cheesesteak Omelette\",\n"
				+ "          \"item_qty\": 1,\n"
				+ "          \"menu_family\": \"106\",\n"
				+ "          \"menu_item_id\": \"123\",\n"
				+ "          \"menu_item_type\": \"M\",\n"
				+ "          \"menu_major_group\": \"100\",\n"
				+ "          \"serial_number\": \"1.0\"\n"
				+ "        }\n"
				+ "      ],\n"
				+ "      \"redemption_code_id\": 493352007,\n"
				+ "      \"revenue_code\": \"\",\n"
				+ "      \"revenue_id\": \"\",\n"
				+ "      \"status\": \"processed\",\n"
				+ "      \"subtotal_amount\": 10,\n"
				+ "      \"transaction_no\": \"12345607172902052025\",\n"
				+ "      \"updated_at\": \"2025-05-02T07:17:30Z\"\n"
				+ "    },\n"
				+ "    \"redemption_code_id\": 493352007,\n"
				+ "    \"redemption_code_pass\": null,\n"
				+ "    \"redemption_id\": 519316277,\n"
				+ "    \"redemption_status\": \"redeemed\",\n"
				+ "    \"redemption_type\": \"RewardRedemption\",\n"
				+ "    \"reward_id\": 14235212608,\n"
				+ "    \"store_number\": \"1000\",\n"
				+ "    \"transferred_to_id\": null,\n"
				+ "    \"transferred_to_type\": null,\n"
				+ "    \"updated_at\": \"2025-05-02T07:17:30Z\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": null,\n"
				+ "        \"loyalty_points\": 0,\n"
				+ "        \"net_balance\": 200,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": 0,\n"
				+ "        \"total_credits\": 200,\n"
				+ "        \"total_debits\": \"0.0\",\n"
				+ "        \"total_lifetime_points\": 200,\n"
				+ "        \"total_point_credits\": 200,\n"
				+ "        \"total_redeemable_visits\": 200,\n"
				+ "        \"total_visits\": 0,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 33,\n"
				+ "        \"user_id\": 455368536\n"
				+ "      },\n"
				+ "      \"anniversary\": null,\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": \"1966-04-04\",\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"455368536\",\n"
				+ "      \"first_name\": \"TestFName07172202052025\",\n"
				+ "      \"gender\": \"Male\",\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-02T07:17:30Z\",\n"
				+ "      \"last_name\": \"TestLName07172202052025\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": 455368536,\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    },\n"
				+ "    \"user_id\": 455368536,\n"
				+ "    \"web\": null\n"
				+ "  }\n"
				+ "}";
		
		return payload ;
	}
	
	
	public String getGiftCheckinPayload(String email) {
		String payload = "{\n"
				+ "  \"content_id\": \"29ddba11-f0a7-498c-ae01-245d3c0bffd8\",\n"
				+ "  \"timestamp\": 1746694657,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"checkins\",\n"
				+ "  \"event_type\": \"gift\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"kafka_offset\": 6308579,\n"
				+ "  \"kafka_partition\": 2,\n"
				+ "  \"is_rate_limit\": false,\n"
				+ "  \"payload\": {\n"
				+ "    \"approved\": true,\n"
				+ "    \"bar_code\": null,\n"
				+ "    \"campaign_id\": null,\n"
				+ "    \"campaign_name\": null,\n"
				+ "    \"campaign_type\": null,\n"
				+ "    \"channel\": null,\n"
				+ "    \"checkin_id\": 21758235095,\n"
				+ "    \"checkin_type\": null,\n"
				+ "    \"created_at\": \"2025-05-08T08:57:16Z\",\n"
				+ "    \"earnable_amount\": null,\n"
				+ "    \"expired_at\": null,\n"
				+ "    \"expiring_on\": null,\n"
				+ "    \"external_uid\": null,\n"
				+ "    \"first_punchh_at_business\": false,\n"
				+ "    \"first_punchh_at_location\": false,\n"
				+ "    \"for_referring_checkin_id\": null,\n"
				+ "    \"for_referring_full_name\": null,\n"
				+ "    \"for_referring_user_id\": null,\n"
				+ "    \"free_punchh_campaign_id\": null,\n"
				+ "    \"gift_reason\": \"Guest Relations\",\n"
				+ "    \"gifted_by_id\": 3195,\n"
				+ "    \"gifted_by_type\": \"Admin\",\n"
				+ "    \"gifted_for_id\": 121415024,\n"
				+ "    \"gifted_for_type\": \"FeedbackReply\",\n"
				+ "    \"location_id\": 408326,\n"
				+ "    \"location_name\": \"AutomationLocation\",\n"
				+ "    \"manual\": null,\n"
				+ "    \"menu_items\": [],\n"
				+ "    \"pending_refresh\": false,\n"
				+ "    \"points_earned\": 1,\n"
				+ "    \"points_spent\": 0,\n"
				+ "    \"punchh_key\": null,\n"
				+ "    \"qr_decoded\": null,\n"
				+ "    \"receipt_amount\": null,\n"
				+ "    \"receipt_date\": null,\n"
				+ "    \"redemption_id\": 0,\n"
				+ "    \"refreshed_at\": null,\n"
				+ "    \"revenue_code\": null,\n"
				+ "    \"revenue_id\": null,\n"
				+ "    \"reviewer_id\": null,\n"
				+ "    \"status\": \"gift\",\n"
				+ "    \"store_number\": \"01\",\n"
				+ "    \"transaction_no\": null,\n"
				+ "    \"unverified_receipt_amount\": null,\n"
				+ "    \"updated_at\": \"2025-05-08T08:57:16Z\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": \"2025-05-06T12:02:17Z\",\n"
				+ "        \"loyalty_points\": 1,\n"
				+ "        \"net_balance\": 4,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": 0,\n"
				+ "        \"total_credits\": 4,\n"
				+ "        \"total_debits\": \"0.0\",\n"
				+ "        \"total_lifetime_points\": 4,\n"
				+ "        \"total_point_credits\": 4,\n"
				+ "        \"total_redeemable_visits\": 4,\n"
				+ "        \"total_visits\": 1,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 0,\n"
				+ "        \"user_id\": 455369971\n"
				+ "      },\n"
				+ "      \"anniversary\": null,\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": \"1966-04-04\",\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"455369971\",\n"
				+ "      \"first_name\": \"TestFName17321106052025\",\n"
				+ "      \"gender\": null,\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-06T12:02:17Z\",\n"
				+ "      \"last_name\": \"TestLName17321106052025\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": 455369971,\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    },\n"
				+ "    \"user_id\": 455369971,\n"
				+ "    \"verifications_count\": null,\n"
				+ "    \"verified_at\": null\n"
				+ "  }\n"
				+ "}";
		return payload ;
		
	}
	
	public String getPostCheckinPayload(String email) {
		String payload = "{\n"
				+ "  \"content_id\": \"2aedcba7-565f-40e6-a3ee-a9d08efc0bc9\",\n"
				+ "  \"timestamp\": 1745847204,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"marketing_notifications\",\n"
				+ "  \"event_type\": \"post_checkin_campaign\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"kafka_offset\": 304277,\n"
				+ "  \"kafka_partition\": 0,\n"
				+ "  \"is_rate_limit\": false,\n"
				+ "  \"payload\": {\n"
				+ "    \"campaign_id\": 63,\n"
				+ "    \"campaign_name\": \"POST - Message\",\n"
				+ "    \"campaign_type\": \"NotificationBearing\",\n"
				+ "    \"checkin_id\": 856350,\n"
				+ "    \"coupon_code\": null,\n"
				+ "    \"coupon_end_date\": null,\n"
				+ "    \"days_of_week\": \"all week\",\n"
				+ "    \"extra_points\": null,\n"
				+ "    \"gift_reason\": null,\n"
				+ "    \"gifted_amount\": null,\n"
				+ "    \"hours_of_day\": \"all day\",\n"
				+ "    \"location_name\": \"\",\n"
				+ "    \"reward_expiring_at\": null,\n"
				+ "    \"reward_expiring_at_tz\": null,\n"
				+ "    \"reward_id\": null,\n"
				+ "    \"reward_name\": null,\n"
				+ "    \"schedule\": \"all day all week\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": \"Gold Level\",\n"
				+ "        \"last_visit\": \"2025-04-28T13:33:22Z\",\n"
				+ "        \"loyalty_points\": 113,\n"
				+ "        \"net_balance\": 183,\n"
				+ "        \"net_debits\": 4,\n"
				+ "        \"pending_points\": 0,\n"
				+ "        \"total_credits\": 187,\n"
				+ "        \"total_debits\": \"4.0\",\n"
				+ "        \"total_lifetime_points\": 187,\n"
				+ "        \"total_point_credits\": 187,\n"
				+ "        \"total_redeemable_visits\": null,\n"
				+ "        \"total_visits\": 16,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": null,\n"
				+ "        \"user_id\": 169469\n"
				+ "      },\n"
				+ "      \"anniversary\": null,\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": null,\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"169469\",\n"
				+ "      \"first_name\": \"Rohit\",\n"
				+ "      \"gender\": \"male\",\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-04-28T13:33:22Z\",\n"
				+ "      \"last_name\": \"Bsr2011\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": 169469,\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    }\n"
				+ "  }\n"
				+ "}";
		return payload ;
		
	}
	
	public String getRedeemableEventPayload() {
		String payload = "{\n"
				+ "  \"content_id\": \"5cf14f35-4b68-4ae8-97d1-b9fccd43bf34\",\n"
				+ "  \"timestamp\": 1745845982,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"redeemables\",\n"
				+ "  \"event_type\": \"\",\n"
				+ "  \"action\": \"update\",\n"
				+ "  \"is_rate_limit\": false,\n"
				+ "  \"payload\": {\n"
				+ "    \"applicable_as_loyalty_redemption\": false,\n"
				+ "    \"created_at\": \"2025-02-28T05:21:51Z\",\n"
				+ "    \"description\": \"Free Tacos Redeemable - $1.00 OFF\",\n"
				+ "    \"discount_amount\": 5,\n"
				+ "    \"discount_channel\": \"all\",\n"
				+ "    \"end_time\": \"2025-05-31T20:15:00Z\",\n"
				+ "    \"expire_redemption_code_with_reward_end_date\": false,\n"
				+ "    \"expiry_date\": null,\n"
				+ "    \"expiry_days\": null,\n"
				+ "    \"meta_data\": \"meta1,meta2\",\n"
				+ "    \"name\": \"Free Tacos\",\n"
				+ "    \"points_required_to_redeem\": 120,\n"
				+ "    \"redeemable_id\": 4009,\n"
				+ "    \"redeemable_image_url\": \"https://res.cloudinary.com/punchh/image/upload/fl_lossy,q_auto/v1/static/punchh-icon-thumb.png\",\n"
				+ "    \"redeemable_properties\": \"Donatable,Size-S|M|L|XL|2XL,merchandize\",\n"
				+ "    \"redemption_expiry\": 120,\n"
				+ "    \"status\": \"activated\",\n"
				+ "    \"updated_at\": \"2025-04-28T13:13:01Z\"\n"
				+ "  }\n"
				+ "}";
		
		return payload ;
		
	}
	
	
	//for braze - reward payload
	
	public String getBrazeRewardPayload(String email) {
		String payload = "{\n"
				+ "  \"content_id\": \"411c7b83-2975-464d-9256-10542120052025\",\n"
				+ "  \"timestamp\": 1746445414,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"rewards\",\n"
				+ "  \"event_type\": \"\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"kafka_offset\": 147739403,\n"
				+ "  \"kafka_partition\": 0,\n"
				+ "  \"is_rate_limit\": false,\n"
				+ "  \"payload\": {\n"
				+ "    \"becomes_available_at\": \"2025-05-05T04:43:17-07:00\",\n"
				+ "    \"campaign_id\": null,\n"
				+ "    \"campaign_name\": null,\n"
				+ "    \"campaign_type\": null,\n"
				+ "    \"created_at\": \"2025-05-05T11:43:17Z\",\n"
				+ "    \"description\": null,\n"
				+ "    \"discount_amount\": 0,\n"
				+ "    \"discount_channel\": null,\n"
				+ "    \"expiring_at\": null,\n"
				+ "    \"expiring_at_tz\": null,\n"
				+ "    \"external_campaign_id\": null,\n"
				+ "    \"franchisee_id\": null,\n"
				+ "    \"gift_reason\": \"Guest Relations\",\n"
				+ "    \"gifted_for_id\": 121408685,\n"
				+ "    \"gifted_for_type\": \"FeedbackReply\",\n"
				+ "    \"meta_data\": null,\n"
				+ "    \"name\": \"Base Redeemable\",\n"
				+ "    \"read_at\": null,\n"
				+ "    \"redeemable_created_at\": \"2025-04-28T12:43:08Z\",\n"
				+ "    \"redeemable_id\": 2827738,\n"
				+ "    \"redemption_id\": null,\n"
				+ "    \"reward_id\": 14235241963,\n"
				+ "    \"reward_image_url\": \"https://res.cloudinary.com/punchh/image/upload/fl_lossy,q_auto/v1/static/punchh-icon-thumb.png\",\n"
				+ "    \"reward_points_redeemed\": 0,\n"
				+ "    \"reward_properties\": null,\n"
				+ "    \"status\": \"unredeemed\",\n"
				+ "    \"store_numbers\": [],\n"
				+ "    \"updated_at\": \"2025-05-05T11:43:17Z\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": null,\n"
				+ "        \"loyalty_points\": null,\n"
				+ "        \"net_balance\": 0,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": null,\n"
				+ "        \"total_credits\": null,\n"
				+ "        \"total_debits\": null,\n"
				+ "        \"total_lifetime_points\": 0,\n"
				+ "        \"total_point_credits\": 0,\n"
				+ "        \"total_redeemable_visits\": 0,\n"
				+ "        \"total_visits\": null,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 0,\n"
				+ "        \"user_id\": 455368548\n"
				+ "      },\n"
				+ "      \"anniversary\": \"1980-04-04\",\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": \"1966-04-04\",\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"455368548\",\n"
				+ "      \"first_name\": \"TestFName10542120052025\",\n"
				+ "      \"gender\": \"Male\",\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-02T08:59:22Z\",\n"
				+ "      \"last_name\": \"TestLName10542120052025\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": 10542120052025,\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    }\n"
				+ "  }\n"
				+ "}";
		return payload ;

	}
	
	
	public String getBrzeGuestEventPayload(String  email) {
		String payload = "{\n"
				+ "  \"content_id\": \"d24e0ba9-106c-4f55-bcee-05592320052025\",\n"
				+ "  \"timestamp\": 1731399223,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"users\",\n"
				+ "  \"event_type\": \"\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"kafka_offset\": 5680002,\n"
				+ "  \"kafka_partition\": 2,\n"
				+ "  \"is_rate_limit\": false,\n"
				+ "  \"payload\": {\n"
				+ "    \"account_balance\": {\n"
				+ "      \"current_membership_level_name\": \"Silver Level\",\n"
				+ "      \"loyalty_points\": 0,\n"
				+ "      \"net_balance\": 2,\n"
				+ "      \"net_debits\": 0,\n"
				+ "      \"pending_points\": 0,\n"
				+ "      \"total_credits\": 2,\n"
				+ "      \"total_debits\": \"0.0\",\n"
				+ "      \"total_lifetime_points\": 2,\n"
				+ "      \"total_point_credits\": 2,\n"
				+ "      \"total_visits\": 0,\n"
				+ "      \"user_id\": 169692\n"
				+ "    },\n"
				+ "    \"business_id\": 2022,\n"
				+ "    \"confirmation_sent_at\": \"2024-11-12T08:13:34Z\",\n"
				+ "    \"created_at\": \"2024-11-12T08:13:33Z\",\n"
				+ "    \"current_sign_in_at\": \"2024-11-12T08:13:33Z\",\n"
				+ "    \"current_sign_in_ip\": \"10.78.24.0\",\n"
				+ "    \"email\": \""+email+"\",\n"
				+ "    \"external_source\": \"\",\n"
				+ "    \"external_source_id\": \"169692\",\n"
				+ "    \"fav_locations\": [],\n"
				+ "    \"favourite_store_numbers\": \"\",\n"
				+ "    \"first_name\": \"Rohit5may-022\",\n"
				+ "    \"guest_type\": \"Loyalty\",\n"
				+ "    \"joined_at\": \"2024-11-12T08:13:33Z\",\n"
				+ "    \"last_activity_at\": \"2024-11-12T08:13:33Z\",\n"
				+ "    \"last_name\": \"Bsr3542\",\n"
				+ "    \"last_sign_in_at\": \"2024-11-12T08:13:33Z\",\n"
				+ "    \"last_sign_in_ip\": \"10.78.24.0\",\n"
				+ "    \"last_user_agent\": \"MyRewards/2.0/2 (x86_64; iOS 10.3; Scale/2.00)\",\n"
				+ "    \"marketing_email_subscription\": true,\n"
				+ "    \"marketing_pn_subscription\": true,\n"
				+ "    \"previous_changes\": [\n"
				+ "      \"id\",\n"
				+ "      \"email\",\n"
				+ "      \"encrypted_password\",\n"
				+ "      \"current_sign_in_at\",\n"
				+ "      \"last_sign_in_at\",\n"
				+ "      \"current_sign_in_ip\",\n"
				+ "      \"last_sign_in_ip\",\n"
				+ "      \"first_name\",\n"
				+ "      \"last_name\",\n"
				+ "      \"authentication_token\",\n"
				+ "      \"joined_at\",\n"
				+ "      \"created_at\",\n"
				+ "      \"updated_at\",\n"
				+ "      \"signup_channel\",\n"
				+ "      \"referral_code\",\n"
				+ "      \"subscription_status\",\n"
				+ "      \"business_id\",\n"
				+ "      \"last_activity_at\"\n"
				+ "    ],\n"
				+ "    \"profile_fields\": [],\n"
				+ "    \"referral_code\": \"Rohi82Bs8080\",\n"
				+ "    \"signup_channel\": \"MobileEmail\",\n"
				+ "    \"sms_subscription\": false,\n"
				+ "    \"terms_and_conditions\": false,\n"
				+ "    \"unsubscribed\": false,\n"
				+ "    \"updated_at\": \"2024-11-12T08:13:37Z\",\n"
				+ "    \"user_external_identifiers\": [],\n"
				+ "    \"user_id\": 169692,\n"
				+ "    \"user_relations\": [],\n"
				+ "    \"user_status\": \"active\"\n"
				+ "  }\n"
				+ "}";
		
		return payload ;
		
	}
	
	public String getBrazeMarketingNotificationPayload(String email) {
		
		String payload = "{\n"
				+ "  \"content_id\": \"9efb2fe8-0b3b-45b6-a2b4-4fba2cee0fd8\",\n"
				+ "  \"timestamp\": 1746792397,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"marketing_notifications\",\n"
				+ "  \"event_type\": \"post_checkin_campaign\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"payload\": {\n"
				+ "    \"campaign_id\": 47230,\n"
				+ "    \"campaign_name\": \"EF POS Checkin Coupon Campaign\",\n"
				+ "    \"campaign_type\": \"NotificationBearing\",\n"
				+ "    \"checkin_id\": 21758851726,\n"
				+ "    \"coupon_code\": \"CSWI8T5D\",\n"
				+ "    \"coupon_end_date\": \"2025-05-18\",\n"
				+ "    \"days_of_week\": \"all week\",\n"
				+ "    \"extra_points\": null,\n"
				+ "    \"gift_reason\": null,\n"
				+ "    \"gifted_amount\": null,\n"
				+ "    \"hours_of_day\": \"all day\",\n"
				+ "    \"location_name\": \"\",\n"
				+ "    \"reward_expiring_at\": null,\n"
				+ "    \"reward_expiring_at_tz\": null,\n"
				+ "    \"reward_id\": null,\n"
				+ "    \"reward_name\": null,\n"
				+ "    \"schedule\": \"all day all week\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": \"2025-05-09T12:06:37Z\",\n"
				+ "        \"loyalty_points\": 1,\n"
				+ "        \"net_balance\": 6,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": 0,\n"
				+ "        \"total_credits\": 6,\n"
				+ "        \"total_debits\": \"0.0\",\n"
				+ "        \"total_lifetime_points\": 6,\n"
				+ "        \"total_point_credits\": 6,\n"
				+ "        \"total_redeemable_visits\": 6,\n"
				+ "        \"total_visits\": 1,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 1,\n"
				+ "        \"user_id\": 455373336\n"
				+ "      },\n"
				+ "      \"anniversary\": \"1980-04-04\",\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": \"1955-04-04\",\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"455373336\",\n"
				+ "      \"first_name\": \"Rohit\",\n"
				+ "      \"gender\": null,\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-09T12:06:37Z\",\n"
				+ "      \"last_name\": \"Bsr3974\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": 455373336,\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    }\n"
				+ "  }\n"
				+ "}";
		
		return payload ;
		
	}
	
	public String getBrazeRedemptionsEventPayload(String email) {
		String payload = "{\n"
				+ "  \"content_id\": \"794593dd-aa77-4e3d-80fc-29519903726e\",\n"
				+ "  \"timestamp\": 1746170255,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"redemptions\",\n"
				+ "  \"event_type\": \"\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"payload\": {\n"
				+ "    \"additional_properties\": \"{\\\"revenue_code\\\":\\\"\\\",\\\"revenue_id\\\":\\\"\\\"}\",\n"
				+ "    \"admin_id\": null,\n"
				+ "    \"bar_code\": \"07172902052025\",\n"
				+ "    \"channel\": \"POS\",\n"
				+ "    \"created_at\": \"2025-05-02T07:17:30Z\",\n"
				+ "    \"expired_at\": null,\n"
				+ "    \"expiring_on\": \"2025-05-02T08:47:30Z\",\n"
				+ "    \"force_message\": null,\n"
				+ "    \"internal_tracking_code\": \"6556227\",\n"
				+ "    \"location_id\": 338762,\n"
				+ "    \"location_name\": \"Adelanto (14200 Highway 395)\",\n"
				+ "    \"points_requested\": 13,\n"
				+ "    \"redeemable_id\": 2826766,\n"
				+ "    \"redeemable_name\": \"DoNotDeleteUsedForWebhook_automation\",\n"
				+ "    \"redeemable_properties\": null,\n"
				+ "    \"redeemed_points\": 10,\n"
				+ "    \"redemption_code\": {\n"
				+ "      \"business_id\": 685,\n"
				+ "      \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "      \"created_at\": \"2025-04-25T12:51:32Z\",\n"
				+ "      \"discount\": 13,\n"
				+ "      \"employee_id\": null,\n"
				+ "      \"location_id\": 338762,\n"
				+ "      \"processed_at\": \"2025-05-02T07:17:30Z\",\n"
				+ "      \"receipt_amount\": 10,\n"
				+ "      \"receipt_datetime\": \"2025-05-02 10:57:32 -0700\",\n"
				+ "      \"redeemable_id\": 2826766,\n"
				+ "      \"redeemed_menu_items\": [\n"
				+ "        {\n"
				+ "          \"item_amount\": 10,\n"
				+ "          \"item_name\": \"Philly Cheesesteak Omelette\",\n"
				+ "          \"item_qty\": 1,\n"
				+ "          \"menu_family\": \"106\",\n"
				+ "          \"menu_item_id\": \"123\",\n"
				+ "          \"menu_item_type\": \"M\",\n"
				+ "          \"menu_major_group\": \"100\",\n"
				+ "          \"serial_number\": \"1.0\"\n"
				+ "        }\n"
				+ "      ],\n"
				+ "      \"redemption_code_id\": 493352007,\n"
				+ "      \"revenue_code\": \"\",\n"
				+ "      \"revenue_id\": \"\",\n"
				+ "      \"status\": \"processed\",\n"
				+ "      \"subtotal_amount\": 10,\n"
				+ "      \"transaction_no\": \"12345607172902052025\",\n"
				+ "      \"updated_at\": \"2025-05-02T07:17:30Z\"\n"
				+ "    },\n"
				+ "    \"redemption_code_id\": 493352007,\n"
				+ "    \"redemption_code_pass\": null,\n"
				+ "    \"redemption_id\": 519316277,\n"
				+ "    \"redemption_status\": \"redeemed\",\n"
				+ "    \"redemption_type\": \"RewardRedemption\",\n"
				+ "    \"reward_id\": 14235212608,\n"
				+ "    \"store_number\": \"1000\",\n"
				+ "    \"transferred_to_id\": null,\n"
				+ "    \"transferred_to_type\": null,\n"
				+ "    \"updated_at\": \"2025-05-02T07:17:30Z\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": null,\n"
				+ "        \"loyalty_points\": 0,\n"
				+ "        \"net_balance\": 200,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": 0,\n"
				+ "        \"total_credits\": 200,\n"
				+ "        \"total_debits\": \"0.0\",\n"
				+ "        \"total_lifetime_points\": 200,\n"
				+ "        \"total_point_credits\": 200,\n"
				+ "        \"total_redeemable_visits\": 200,\n"
				+ "        \"total_visits\": 0,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 33,\n"
				+ "        \"user_id\": 455368536\n"
				+ "      },\n"
				+ "      \"anniversary\": \"1980-04-04\",\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": \"1966-04-04\",\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"455368536\",\n"
				+ "      \"first_name\": \"TestFName07172202052025\",\n"
				+ "      \"gender\": \"Male\",\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-02T07:17:30Z\",\n"
				+ "      \"last_name\": \"TestLName07172202052025\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": \"9874638295\",\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": 455368536,\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    },\n"
				+ "    \"user_id\": 455368536,\n"
				+ "    \"web\": null\n"
				+ "  }\n"
				+ "}";
		return payload ;
		
	}
	
	public String getBrazeTransactionalNotificationEventPayload(String email) {
		String payload = "{\n"
				+ "  \"content_id\": \"7a278ed7-757b-420c-b8cc-d0195ece00b8\",\n"
				+ "  \"timestamp\": 1746170427,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"transactional_notifications\",\n"
				+ "  \"event_type\": \"confirmation_email\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"payload\": {\n"
				+ "    \"account_balance\": {\n"
				+ "      \"banked_currency\": null,\n"
				+ "      \"current_membership_level_name\": null,\n"
				+ "      \"last_visit\": null,\n"
				+ "      \"loyalty_points\": null,\n"
				+ "      \"net_balance\": 0,\n"
				+ "      \"net_debits\": 0,\n"
				+ "      \"pending_points\": null,\n"
				+ "      \"total_credits\": null,\n"
				+ "      \"total_debits\": null,\n"
				+ "      \"total_lifetime_points\": 0,\n"
				+ "      \"total_point_credits\": 0,\n"
				+ "      \"total_redeemable_visits\": 0,\n"
				+ "      \"total_visits\": null,\n"
				+ "      \"unbanked_points\": null,\n"
				+ "      \"unredeemed_cards\": 0,\n"
				+ "      \"user_id\": 455368542\n"
				+ "    },\n"
				+ "    \"anniversary\": null,\n"
				+ "    \"avatar_remote_url\": null,\n"
				+ "    \"birthday\": \"1966-04-04\",\n"
				+ "    \"email\": \""+email+"\",\n"
				+ "    \"email_confirmation_url\": \"https://dashboard.punchh.com/customers/confirmation.iframe?confirmation_token=sxyrRQojpxbEmLonD9o2&slug=deltaco\",\n"
				+ "    \"external_source\": \"\",\n"
				+ "    \"external_source_id\": \"455368542\",\n"
				+ "    \"first_name\": \"TestFName07202702052025\",\n"
				+ "    \"gender\": null,\n"
				+ "    \"guest_type\": \"Loyalty\",\n"
				+ "    \"last_activity_at\": \"2025-05-02T07:20:27Z\",\n"
				+ "    \"last_name\": \"TestLName07202702052025\",\n"
				+ "    \"marketing_email_subscription\": true,\n"
				+ "    \"marketing_pn_subscription\": true,\n"
				+ "    \"phone\": null,\n"
				+ "    \"preferred_locale\": null,\n"
				+ "    \"reset_password_url\": null,\n"
				+ "    \"secondary_email\": null,\n"
				+ "    \"signup_channel\": \"MobileEmail\",\n"
				+ "    \"sms_subscription\": false,\n"
				+ "    \"unsubscribe_reason\": null,\n"
				+ "    \"unsubscribed\": false,\n"
				+ "    \"user_id\": 455368542,\n"
				+ "    \"user_status\": \"active\"\n"
				+ "  }\n"
				+ "}" ; 
		
		return payload ;
		
	}
	
	public String getBrazeGiftCheckinpayload(String email) {
		String payload = "{\n"
				+ "  \"content_id\": \"29ddba11-f0a7-498c-ae01-245d3c0bffd8\",\n"
				+ "  \"timestamp\": 1746694657,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"checkins\",\n"
				+ "  \"event_type\": \"gift\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"kafka_offset\": 6319235,\n"
				+ "  \"kafka_partition\": 2,\n"
				+ "  \"is_rate_limit\": false,\n"
				+ "  \"payload\": {\n"
				+ "    \"approved\": true,\n"
				+ "    \"bar_code\": null,\n"
				+ "    \"campaign_id\": null,\n"
				+ "    \"campaign_name\": null,\n"
				+ "    \"campaign_type\": null,\n"
				+ "    \"channel\": null,\n"
				+ "    \"checkin_id\": 21758235095,\n"
				+ "    \"checkin_type\": null,\n"
				+ "    \"created_at\": \"2025-05-08T08:57:16Z\",\n"
				+ "    \"earnable_amount\": null,\n"
				+ "    \"expired_at\": null,\n"
				+ "    \"expiring_on\": null,\n"
				+ "    \"external_uid\": null,\n"
				+ "    \"first_punchh_at_business\": false,\n"
				+ "    \"first_punchh_at_location\": false,\n"
				+ "    \"for_referring_checkin_id\": null,\n"
				+ "    \"for_referring_full_name\": null,\n"
				+ "    \"for_referring_user_id\": null,\n"
				+ "    \"free_punchh_campaign_id\": null,\n"
				+ "    \"gift_reason\": \"Guest Relations\",\n"
				+ "    \"gifted_by_id\": 3195,\n"
				+ "    \"gifted_by_type\": \"Admin\",\n"
				+ "    \"gifted_for_id\": 121415024,\n"
				+ "    \"gifted_for_type\": \"FeedbackReply\",\n"
				+ "    \"location_id\": 408326,\n"
				+ "    \"location_name\": \"AutomationLocation\",\n"
				+ "    \"manual\": null,\n"
				+ "    \"menu_items\": [],\n"
				+ "    \"pending_refresh\": false,\n"
				+ "    \"points_earned\": 1,\n"
				+ "    \"points_spent\": 0,\n"
				+ "    \"punchh_key\": null,\n"
				+ "    \"qr_decoded\": null,\n"
				+ "    \"receipt_amount\": null,\n"
				+ "    \"receipt_date\": null,\n"
				+ "    \"redemption_id\": 0,\n"
				+ "    \"refreshed_at\": null,\n"
				+ "    \"revenue_code\": null,\n"
				+ "    \"revenue_id\": null,\n"
				+ "    \"reviewer_id\": null,\n"
				+ "    \"status\": \"gift\",\n"
				+ "    \"store_number\": \"01\",\n"
				+ "    \"transaction_no\": null,\n"
				+ "    \"unverified_receipt_amount\": null,\n"
				+ "    \"updated_at\": \"2025-05-08T08:57:16Z\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": \"2025-05-06T12:02:17Z\",\n"
				+ "        \"loyalty_points\": 1,\n"
				+ "        \"net_balance\": 4,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": 0,\n"
				+ "        \"total_credits\": 4,\n"
				+ "        \"total_debits\": \"0.0\",\n"
				+ "        \"total_lifetime_points\": 4,\n"
				+ "        \"total_point_credits\": 4,\n"
				+ "        \"total_redeemable_visits\": 4,\n"
				+ "        \"total_visits\": 1,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 0,\n"
				+ "        \"user_id\": 455369971\n"
				+ "      },\n"
				+ "      \"anniversary\": null,\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": \"1966-04-04\",\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"455369971\",\n"
				+ "      \"first_name\": \"TestFName17321106052025\",\n"
				+ "      \"gender\": null,\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-06T12:02:17Z\",\n"
				+ "      \"last_name\": \"TestLName17321106052025\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": 455369971,\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    },\n"
				+ "    \"user_id\": 455369971,\n"
				+ "    \"verifications_count\": null,\n"
				+ "    \"verified_at\": null\n"
				+ "  }\n"
				+ "}";
		
		return payload ;
		
	}
	
	
	public String getBrazeLoyaltyCheckinEventPayload(String email) {
		String payload = "{\n"
				+ "  \"content_id\": \"be5f014a-2f51-408a-abf1-75666bc82444\",\n"
				+ "  \"timestamp\": 1746532961,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"checkins\",\n"
				+ "  \"event_type\": \"loyalty\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"kafka_offset\": 2613604,\n"
				+ "  \"kafka_partition\": 1,\n"
				+ "  \"is_rate_limit\": false,\n"
				+ "  \"payload\": {\n"
				+ "    \"approved\": true,\n"
				+ "    \"bar_code\": \"17321506052025\",\n"
				+ "    \"campaign_id\": null,\n"
				+ "    \"campaign_name\": null,\n"
				+ "    \"campaign_type\": null,\n"
				+ "    \"channel\": \"POS\",\n"
				+ "    \"checkin_id\": 21757099949,\n"
				+ "    \"checkin_type\": \"PosCheckin\",\n"
				+ "    \"created_at\": \"2025-05-06T12:02:17Z\",\n"
				+ "    \"earnable_amount\": 50,\n"
				+ "    \"expired_at\": null,\n"
				+ "    \"expiring_on\": null,\n"
				+ "    \"external_uid\": \"17321506052025\",\n"
				+ "    \"first_punchh_at_business\": true,\n"
				+ "    \"first_punchh_at_location\": true,\n"
				+ "    \"for_referring_checkin_id\": null,\n"
				+ "    \"for_referring_full_name\": null,\n"
				+ "    \"for_referring_user_id\": null,\n"
				+ "    \"free_punchh_campaign_id\": null,\n"
				+ "    \"gift_reason\": null,\n"
				+ "    \"gifted_by_id\": null,\n"
				+ "    \"gifted_by_type\": null,\n"
				+ "    \"gifted_for_id\": null,\n"
				+ "    \"gifted_for_type\": null,\n"
				+ "    \"location_id\": 408326,\n"
				+ "    \"location_name\": \"AutomationLocation\",\n"
				+ "    \"manual\": null,\n"
				+ "    \"menu_items\": [\n"
				+ "      {\n"
				+ "        \"item_amount\": 100,\n"
				+ "        \"item_name\": \"Margherita\",\n"
				+ "        \"item_qty\": 1,\n"
				+ "        \"menu_family\": \"106\",\n"
				+ "        \"menu_item_id\": \"110\",\n"
				+ "        \"menu_item_type\": \"M\",\n"
				+ "        \"menu_major_group\": \"100\",\n"
				+ "        \"serial_number\": \"1.0\"\n"
				+ "      },\n"
				+ "      {\n"
				+ "        \"item_amount\": 110,\n"
				+ "        \"item_name\": \"Pizza\",\n"
				+ "        \"item_qty\": 1,\n"
				+ "        \"menu_family\": \"106\",\n"
				+ "        \"menu_item_id\": \"111\",\n"
				+ "        \"menu_item_type\": \"M\",\n"
				+ "        \"menu_major_group\": \"100\",\n"
				+ "        \"serial_number\": \"1.0\"\n"
				+ "      }\n"
				+ "    ],\n"
				+ "    \"pending_refresh\": false,\n"
				+ "    \"points_earned\": 1,\n"
				+ "    \"points_spent\": 0,\n"
				+ "    \"punchh_key\": \"73215060520\",\n"
				+ "    \"qr_decoded\": null,\n"
				+ "    \"receipt_amount\": 50,\n"
				+ "    \"receipt_date\": null,\n"
				+ "    \"redemption_id\": 0,\n"
				+ "    \"refreshed_at\": null,\n"
				+ "    \"revenue_code\": null,\n"
				+ "    \"revenue_id\": null,\n"
				+ "    \"reviewer_id\": null,\n"
				+ "    \"status\": \"loyalty\",\n"
				+ "    \"store_number\": \"01\",\n"
				+ "    \"transaction_no\": \"1234565445717321506052025\",\n"
				+ "    \"unverified_receipt_amount\": null,\n"
				+ "    \"updated_at\": \"2025-05-06T12:02:17Z\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": \"2025-05-06T12:02:17Z\",\n"
				+ "        \"loyalty_points\": 1,\n"
				+ "        \"net_balance\": 1,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": 0,\n"
				+ "        \"total_credits\": 1,\n"
				+ "        \"total_debits\": \"0.0\",\n"
				+ "        \"total_lifetime_points\": 1,\n"
				+ "        \"total_point_credits\": 1,\n"
				+ "        \"total_redeemable_visits\": 1,\n"
				+ "        \"total_visits\": 1,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 0,\n"
				+ "        \"user_id\": 455369971\n"
				+ "      },\n"
				+ "      \"anniversary\": null,\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": \"1966-04-04\",\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"455369971\",\n"
				+ "      \"first_name\": \"TestFName17321106052025\",\n"
				+ "      \"gender\": null,\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-06T12:02:17Z\",\n"
				+ "      \"last_name\": \"TestLName17321106052025\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": 455369971,\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    },\n"
				+ "    \"user_id\": 455369971,\n"
				+ "    \"verifications_count\": null,\n"
				+ "    \"verified_at\": null\n"
				+ "  }\n"
				+ "}";
		
		return payload ;
	}
	
	
	public String getBrazeCouponIssuanceEventPayload(String email) {
		String payload = "{\n"
				+ "  \"content_id\": \"22af00fe-ff02-45a1-a098-6a11f5cfc122\",\n"
				+ "  \"timestamp\": 1746792397,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"coupons\",\n"
				+ "  \"event_type\": \"\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"payload\": {\n"
				+ "    \"app_device_id\": null,\n"
				+ "    \"applicable_flat_discount\": 2,\n"
				+ "    \"applicable_percentage_discount\": 0,\n"
				+ "    \"bar_code\": null,\n"
				+ "    \"campaign_name\": \"EF POS Coupon Campaign - $2\",\n"
				+ "    \"code\": \"CSWI8T5D\",\n"
				+ "    \"coupon_campaign_id\": 146493,\n"
				+ "    \"coupon_id\": 2259315855,\n"
				+ "    \"coupon_type\": \"discount\",\n"
				+ "    \"created_at\": \"2025-05-09T12:06:37Z\",\n"
				+ "    \"discount\": null,\n"
				+ "    \"email\": \"rohit+bsr3974@punchh.com\",\n"
				+ "    \"employee_id\": null,\n"
				+ "    \"expiry_at\": \"2025-05-19T06:59:59Z\",\n"
				+ "    \"gift_count\": null,\n"
				+ "    \"location_id\": null,\n"
				+ "    \"processed_at\": null,\n"
				+ "    \"receipt_amount\": null,\n"
				+ "    \"receipt_datetime\": null,\n"
				+ "    \"receipt_subtotal_amount\": null,\n"
				+ "    \"redeemable\": null,\n"
				+ "    \"redeemed_menu_items\": [],\n"
				+ "    \"revenue_code\": null,\n"
				+ "    \"revenue_id\": null,\n"
				+ "    \"status\": \"issued\",\n"
				+ "    \"transaction_no\": null,\n"
				+ "    \"updated_at\": \"2025-05-09T12:06:37Z\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": \"2025-05-09T12:06:37Z\",\n"
				+ "        \"loyalty_points\": 1,\n"
				+ "        \"net_balance\": 6,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": 0,\n"
				+ "        \"total_credits\": 6,\n"
				+ "        \"total_debits\": \"0.0\",\n"
				+ "        \"total_lifetime_points\": 6,\n"
				+ "        \"total_point_credits\": 6,\n"
				+ "        \"total_redeemable_visits\": 6,\n"
				+ "        \"total_visits\": 1,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 1,\n"
				+ "        \"user_id\": 455373336\n"
				+ "      },\n"
				+ "      \"anniversary\": null,\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": null,\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"455373336\",\n"
				+ "      \"first_name\": \"Rohit\",\n"
				+ "      \"gender\": null,\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-09T12:06:37Z\",\n"
				+ "      \"last_name\": \"Bsr3974\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": 455373336,\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    },\n"
				+ "    \"user_coupon_redemption_id\": null,\n"
				+ "    \"user_id\": 455373336\n"
				+ "  }\n"
				+ "}";
		return payload ;
	}
	
	
	public String getBrazeCouponRedemptionsEventPayload(String email) {
		String payload = "{\n"
				+ "  \"content_id\": \"a77dbf7f-eaac-4c81-a2c1-15e8fef59faa\",\n"
				+ "  \"timestamp\": 1746792923,\n"
				+ "  \"business_id\": 2022,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"automationtwentythree\",\n"
				+ "  \"event_name\": \"user_coupon_redemptions\",\n"
				+ "  \"event_type\": \"\",\n"
				+ "  \"action\": \"create\",\n"
				+ "  \"payload\": {\n"
				+ "    \"app_device_id\": null,\n"
				+ "    \"applicable_flat_discount\": 2,\n"
				+ "    \"applicable_percentage_discount\": 0,\n"
				+ "    \"bar_code\": \"08779941323\",\n"
				+ "    \"campaign_name\": \"EF POS Coupon Campaign - $2\",\n"
				+ "    \"code\": \"CSWI8T5D\",\n"
				+ "    \"coupon_campaign_id\": 146493,\n"
				+ "    \"coupon_id\": 2259315855,\n"
				+ "    \"coupon_type\": \"discount\",\n"
				+ "    \"created_at\": \"2025-05-09T12:15:09Z\",\n"
				+ "    \"discount\": 2,\n"
				+ "    \"email\": \"rohit+bsr3974@punchh.com\",\n"
				+ "    \"employee_id\": \"234567\",\n"
				+ "    \"expiry_at\": \"2025-05-19T06:59:59Z\",\n"
				+ "    \"gift_count\": null,\n"
				+ "    \"location_id\": 408326,\n"
				+ "    \"processed_at\": \"2025-05-09T12:15:09Z\",\n"
				+ "    \"receipt_amount\": 5.75,\n"
				+ "    \"receipt_datetime\": \"2025-04-29T06:18:00Z\",\n"
				+ "    \"receipt_subtotal_amount\": 5.75,\n"
				+ "    \"redeemable\": null,\n"
				+ "    \"redeemed_menu_items\": [\n"
				+ "      {\n"
				+ "        \"item_amount\": 2.75,\n"
				+ "        \"item_name\": \"Sandwich\",\n"
				+ "        \"item_qty\": 1,\n"
				+ "        \"menu_family\": \"107\",\n"
				+ "        \"menu_item_id\": \"1001\",\n"
				+ "        \"menu_item_type\": \"M\",\n"
				+ "        \"menu_major_group\": \"242\",\n"
				+ "        \"serial_number\": \"1\"\n"
				+ "      }\n"
				+ "    ],\n"
				+ "    \"revenue_code\": \"123455\",\n"
				+ "    \"revenue_id\": \"1235\",\n"
				+ "    \"status\": \"honored\",\n"
				+ "    \"transaction_no\": \"3602762323\",\n"
				+ "    \"updated_at\": \"2025-05-09T12:15:09Z\",\n"
				+ "    \"user\": {\n"
				+ "      \"account_balance\": {\n"
				+ "        \"banked_currency\": null,\n"
				+ "        \"current_membership_level_name\": null,\n"
				+ "        \"last_visit\": \"2025-05-09T12:15:23Z\",\n"
				+ "        \"loyalty_points\": 2,\n"
				+ "        \"net_balance\": 7,\n"
				+ "        \"net_debits\": 0,\n"
				+ "        \"pending_points\": 0,\n"
				+ "        \"total_credits\": 7,\n"
				+ "        \"total_debits\": \"0.0\",\n"
				+ "        \"total_lifetime_points\": 7,\n"
				+ "        \"total_point_credits\": 7,\n"
				+ "        \"total_redeemable_visits\": 7,\n"
				+ "        \"total_visits\": 2,\n"
				+ "        \"unbanked_points\": null,\n"
				+ "        \"unredeemed_cards\": 1,\n"
				+ "        \"user_id\": 455373336\n"
				+ "      },\n"
				+ "      \"anniversary\": null,\n"
				+ "      \"avatar_remote_url\": null,\n"
				+ "      \"birthday\": null,\n"
				+ "      \"email\": \""+email+"\",\n"
				+ "      \"external_source\": \"\",\n"
				+ "      \"external_source_id\": \"455373336\",\n"
				+ "      \"first_name\": \"Rohit\",\n"
				+ "      \"gender\": null,\n"
				+ "      \"guest_type\": \"Loyalty\",\n"
				+ "      \"last_activity_at\": \"2025-05-09T12:06:37Z\",\n"
				+ "      \"last_name\": \"Bsr3974\",\n"
				+ "      \"marketing_email_subscription\": true,\n"
				+ "      \"marketing_pn_subscription\": true,\n"
				+ "      \"phone\": null,\n"
				+ "      \"preferred_locale\": null,\n"
				+ "      \"secondary_email\": null,\n"
				+ "      \"signup_channel\": \"MobileEmail\",\n"
				+ "      \"sms_subscription\": false,\n"
				+ "      \"unsubscribe_reason\": null,\n"
				+ "      \"unsubscribed\": false,\n"
				+ "      \"user_id\": 455373336,\n"
				+ "      \"user_status\": \"active\"\n"
				+ "    },\n"
				+ "    \"user_coupon_redemption_id\": 25740033,\n"
				+ "    \"user_id\": 455373336\n"
				+ "  }\n"
				+ "}";
		
		return payload ;
		
	}
	
	public String getBrazeGuestUpdatePayload(String email) {
		String payload="{\n"
				+ "  \"content_id\": \"21f0ff73-d4a8-4943-9f05-914c7bc7b0a0\",\n"
				+ "  \"timestamp\": 1747940946,\n"
				+ "  \"business_id\": 7,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"fazolis\",\n"
				+ "  \"event_name\": \"users\",\n"
				+ "  \"event_type\": \"\",\n"
				+ "  \"action\": \"update\",\n"
				+ "  \"kafka_offset\": 1655030,\n"
				+ "  \"kafka_partition\": 0,\n"
				+ "  \"is_rate_limit\": false,\n"
				+ "  \"payload\": {\n"
				+ "    \"account_balance\": {\n"
				+ "      \"current_membership_level_name\": \"Silver Level\",\n"
				+ "      \"last_visit\": \"2025-05-22T19:07:59Z\",\n"
				+ "      \"loyalty_points\": 6,\n"
				+ "      \"net_balance\": 8,\n"
				+ "      \"net_debits\": 0,\n"
				+ "      \"pending_points\": 0,\n"
				+ "      \"total_credits\": 8,\n"
				+ "      \"total_debits\": \"0.0\",\n"
				+ "      \"total_lifetime_points\": 8,\n"
				+ "      \"total_point_credits\": 8,\n"
				+ "      \"total_visits\": 2,\n"
				+ "      \"user_id\": 170115\n"
				+ "    },\n"
				+ "    \"business_id\": 7,\n"
				+ "    \"confirmation_sent_at\": \"2025-05-22T19:05:49Z\",\n"
				+ "    \"created_at\": \"2025-05-22T19:05:49Z\",\n"
				+ "    \"current_sign_in_at\": \"2025-05-22T19:05:49Z\",\n"
				+ "    \"current_sign_in_ip\": \"127.0.0.1\",\n"
				+ "    \"email\": \""+email+"\",\n"
				+ "    \"external_source\": \"\",\n"
				+ "    \"external_source_id\": \"170115\",\n"
				+ "    \"fav_locations\": [],\n"
				+ "    \"favourite_store_numbers\": \"\",\n"
				+ "    \"first_name\": \"Rohitt\",\n"
				+ "    \"guest_type\": \"Loyalty\",\n"
				+ "    \"joined_at\": \"2025-05-22T19:05:49Z\",\n"
				+ "    \"last_activity_at\": \"2025-05-22T19:07:51Z\",\n"
				+ "    \"last_name\": \"Bsr3985\",\n"
				+ "    \"last_sign_in_at\": \"2025-05-22T19:05:49Z\",\n"
				+ "    \"last_sign_in_ip\": \"127.0.0.1\",\n"
				+ "    \"last_user_agent\": \"MyRewards/2.0/2 (x86_64; iOS 10.3; Scale/2.00)\",\n"
				+ "    \"marketing_email_subscription\": true,\n"
				+ "    \"marketing_pn_subscription\": true,\n"
				+ "    \"preferred_locale\": \"en\",\n"
				+ "    \"previous_changes\": [\n"
				+ "      \"updated_at\",\n"
				+ "      \"zip_code\",\n"
				+ "      \"first_name\"\n"
				+ "    ],\n"
				+ "    \"profile_fields\": [],\n"
				+ "    \"referral_code\": \"Ro85Bb52222\",\n"
				+ "    \"signup_channel\": \"MobileEmail\",\n"
				+ "    \"sms_subscription\": false,\n"
				+ "    \"terms_and_conditions\": false,\n"
				+ "    \"time_zone\": \"Asia/Kolkata\",\n"
				+ "    \"unsubscribed\": false,\n"
				+ "    \"updated_at\": \"2025-05-22T19:08:55Z\",\n"
				+ "    \"user_external_identifiers\": [],\n"
				+ "    \"user_id\": 170115,\n"
				+ "    \"user_relations\": [],\n"
				+ "    \"user_status\": \"active\",\n"
				+	" \"zip_code\": \"98030\"\n"
				+ "  }\n"
				+ "}";
		return payload ;
	}
	
	// used to get payload for create, delete and update events for guest
	public String getBrazeGuestCreateDeleteAndUpdatePayload(String email ,String actionType, String previousChanges) {
		
		String payload = "{\n"
				+ "  \"content_id\": \"607f6977-5cb2-400f-8291-079d12fb32a2\",\n"
				+ "  \"timestamp\": 1748243305,\n"
				+ "  \"business_id\": 7,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"fazolis\",\n"
				+ "  \"event_name\": \"users\",\n"
				+ "  \"event_type\": \"\",\n"
				+ "  \"action\": \""+actionType+"\",\n"
				+ "  \"kafka_offset\": 1655669,\n"
				+ "  \"kafka_partition\": 0,\n"
				+ "  \"is_rate_limit\": false,\n"
				+ "  \"payload\": {\n"
				+ "    \"account_balance\": {\n"
				+ "      \"current_membership_level_name\": \"Silver Level\",\n"
				+ "      \"loyalty_points\": 0,\n"
				+ "      \"net_balance\": 2,\n"
				+ "      \"net_debits\": 0,\n"
				+ "      \"pending_points\": 0,\n"
				+ "      \"total_credits\": 2,\n"
				+ "      \"total_debits\": \"0.0\",\n"
				+ "      \"total_lifetime_points\": 2,\n"
				+ "      \"total_point_credits\": 2,\n"
				+ "      \"total_visits\": 0,\n"
				+ "      \"user_id\": 170119\n"
				+ "    },\n"
				+ "    \"address_line1\": \"Mi Road\",\n"
				+ "    \"anniversary\": \"2016-02-02\",\n"
				+ "    \"birthday\": \"1991-02-03\",\n"
				+ "    \"business_id\": 7,\n"
				+ "    \"city\": \"Jaipur\",\n"
				+ "    \"confirmation_sent_at\": \"2025-05-26T06:56:24Z\",\n"
				+ "    \"created_at\": \"2025-05-23T15:34:16Z\",\n"
				+ "    \"current_sign_in_at\": \"2025-05-23T15:34:16Z\",\n"
				+ "    \"current_sign_in_ip\": \"127.0.0.1\",\n"
				+ "    \"email\": \""+email+"\",\n"
				+ "    \"external_source\": \"\",\n"
				+ "    \"external_source_id\": \"170119\",\n"
				+ "    \"fav_locations\": [\n"
				+ "      {\n"
				+ "        \"business_id\": 7,\n"
				+ "        \"business_uuid\": \"57efe5f1-06cc-40df-8388-24026c45c8e4\",\n"
				+ "        \"channel\": \"Favourite\",\n"
				+ "        \"created_at\": \"2025-05-26T06:51:24Z\",\n"
				+ "        \"location_id\": 351110,\n"
				+ "        \"updated_at\": \"2025-05-26T06:51:24Z\",\n"
				+ "        \"user_favourite_location_id\": 119409,\n"
				+ "        \"user_id\": 170119\n"
				+ "      }\n"
				+ "    ],\n"
				+ "    \"favourite_store_numbers\": \"032023005\",\n"
				+ "    \"first_name\": \"Rohitt\",\n"
				+ "    \"gender\": \"male\",\n"
				+ "    \"guest_type\": \"Loyalty\",\n"
				+ "    \"joined_at\": \"2025-05-23T15:34:16Z\",\n"
				+ "    \"last_activity_at\": \"2025-05-23T15:34:16Z\",\n"
				+ "    \"last_name\": \"Bsr3989\",\n"
				+ "    \"last_sign_in_at\": \"2025-05-23T15:34:16Z\",\n"
				+ "    \"last_sign_in_ip\": \"127.0.0.1\",\n"
				+ "    \"last_user_agent\": \"MyRewards/2.0/2 (x86_64; iOS 10.3; Scale/2.00)\",\n"
				+ "    \"marketing_email_subscription\": true,\n"
				+ "    \"marketing_pn_subscription\": true,\n"
				+ "    \"phone\": \"5678567878\",\n"
				+ "    \"preferred_locale\": \"en\",\n"
				+ "    \"previous_changes\": ["+previousChanges+"],\n"
				+ "    \"profile_fields\": [],\n"
				+ "    \"referral_code\": \"Roh39896880\",\n"
				+ "    \"secondary_email\": \"rohit+bsr398999@punchh.com\",\n"
				+ "    \"signup_channel\": \"MobileEmail\",\n"
				+ "    \"sms_subscription\": false,\n"
				+ "    \"state\": \"Rajasthan\",\n"
				+ "    \"terms_and_conditions\": true,\n"
				+ "    \"time_zone\": \"Asia/Kolkata\",\n"
				+ "    \"title\": \"Mr.\",\n"
				+ "    \"unsubscribe_reason\": \"By User\",\n"
				+ "    \"unsubscribed\": false,\n"
				+ "    \"updated_at\": \"2025-05-26T07:08:18Z\",\n"
				+ "    \"user_external_identifiers\": [],\n"
				+ "    \"user_id\": 170119,\n"
				+ "    \"user_relations\": [],\n"
				+ "    \"user_status\": \"active\",\n"
				+ "    \"zip_code\": \"302012\"\n"
				+ "  }\n"
				+ "}";
		
		return payload ;
		
	}
	
	
	//Braze payloads for Transactional Events - usersignup and for confirmation email
	public String getBrazePayloadForTransactionalNotificationsEventType(String email , String actionType , String eventType) {
		String payload = "{\n"
				+ "  \"content_id\": \"2aaf2213-43fd-42d7-91ef-e8aa568ef040\",\n"
				+ "  \"timestamp\": 1747940623,\n"
				+ "  \"business_id\": 7,\n"
				+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
				+ "  \"business_slug\": \"fazolis\",\n"
				+ "  \"event_name\": \"transactional_notifications\",\n"
				+ "  \"event_type\": \""+eventType+"\",\n"
				+ "  \"action\": \""+actionType+"\",\n"
				+ "  \"kafka_offset\": 254026,\n"
				+ "  \"kafka_partition\": 0,\n"
				+ "  \"is_rate_limit\": false,\n"
				+ "  \"payload\": {\n"
				+ "    \"account_balance\": {\n"
				+ "      \"banked_currency\": null,\n"
				+ "      \"current_membership_level_name\": \"Silver Level\",\n"
				+ "      \"last_visit\": null,\n"
				+ "      \"loyalty_points\": 0,\n"
				+ "      \"net_balance\": 2,\n"
				+ "      \"net_debits\": 0,\n"
				+ "      \"pending_points\": 0,\n"
				+ "      \"total_credits\": 2,\n"
				+ "      \"total_debits\": \"0.0\",\n"
				+ "      \"total_lifetime_points\": 2,\n"
				+ "      \"total_point_credits\": 2,\n"
				+ "      \"total_redeemable_visits\": null,\n"
				+ "      \"total_visits\": 0,\n"
				+ "      \"unbanked_points\": null,\n"
				+ "      \"unredeemed_cards\": null,\n"
				+ "      \"user_id\": 170114\n"
				+ "    },\n"
				+ "    \"anniversary\": null,\n"
				+ "    \"avatar_remote_url\": null,\n"
				+ "    \"birthday\": null,\n"
				+ "    \"email\": \""+email+"\",\n"
				+ "    \"email_confirmation_url\": null,\n"
				+ "    \"external_source\": \"\",\n"
				+ "    \"external_source_id\": \"170114\",\n"
				+ "    \"first_name\": \"Rohit\",\n"
				+ "    \"gender\": null,\n"
				+ "    \"guest_type\": \"Loyalty\",\n"
				+ "    \"last_activity_at\": \"2025-05-22T19:02:42Z\",\n"
				+ "    \"last_name\": \"Bsr3984\",\n"
				+ "    \"marketing_email_subscription\": true,\n"
				+ "    \"marketing_pn_subscription\": true,\n"
				+ "    \"phone\": null,\n"
				+ "    \"preferred_locale\": null,\n"
				+ "    \"reset_password_url\": null,\n"
				+ "    \"secondary_email\": null,\n"
				+ "    \"signup_channel\": \"MobileEmail\",\n"
				+ "    \"sms_subscription\": false,\n"
				+ "    \"unsubscribe_reason\": null,\n"
				+ "    \"unsubscribed\": false,\n"
				+ "    \"user_id\": 170114,\n"
				+ "    \"user_status\": \"active\"\n"
				+ "  }\n"
				+ "}";
		
		return payload ;
		
	}
	
	
	//Braze payloads for Transactional Events - RedemptionApplied
		public String getBrazePayloadForTransactionalNotificationsEventTypeRedemptionApplied(String email , String actionType , String eventType) {
			String payload = "{\n"
					+ "  \"content_id\": \"70169660-8dff-4d4d-aeda-84303b9345e2\",\n"
					+ "  \"timestamp\": 1747940887,\n"
					+ "  \"business_id\": 2022,\n"
					+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
					+ "  \"business_slug\": \"automationtwentythree\",\n"
					+ "  \"event_name\": \"transactional_notifications\",\n"
					+ "  \"event_type\": \"redemption_applied\",\n"
					+ "  \"action\": \"create\",\n"
					+ "  \"payload\": {\n"
					+ "    \"discount_amount\": 2.75,\n"
					+ "    \"internal_tracking_code\": \"1567603\",\n"
					+ "    \"location_name\": \"032023 Location 001-04-AAA\",\n"
					+ "    \"processed_at\": \"2025-05-22T19:07:51Z\",\n"
					+ "    \"reward_name\": \"Base Redeemable\",\n" 
					+ "    \"user\": {\n"
					+ "      \"account_balance\": {\n"
					+ "        \"banked_currency\": null,\n"
					+ "        \"current_membership_level_name\": \"Silver Level\",\n"
					+ "        \"last_visit\": \"2025-05-22T19:07:59Z\",\n"
					+ "        \"loyalty_points\": 6,\n"
					+ "        \"net_balance\": 8,\n"
					+ "        \"net_debits\": 0,\n"
					+ "        \"pending_points\": 0,\n"
					+ "        \"total_credits\": 8,\n"
					+ "        \"total_debits\": \"0.0\",\n"
					+ "        \"total_lifetime_points\": 8,\n"
					+ "        \"total_point_credits\": 8,\n"
					+ "        \"total_redeemable_visits\": null,\n"
					+ "        \"total_visits\": 2,\n"
					+ "        \"unbanked_points\": null,\n"
					+ "        \"unredeemed_cards\": null,\n"
					+ "        \"user_id\": 170115\n"
					+ "      },\n"
					+ "      \"anniversary\": null,\n"
					+ "      \"avatar_remote_url\": null,\n"
					+ "      \"birthday\": null,\n"
					+ "      \"email\": \""+email+"\",\n"
					+ "      \"external_source\": \"\",\n"
					+ "      \"external_source_id\": \"170115\",\n"
					+ "      \"first_name\": \"Rohit\",\n"
					+ "      \"gender\": null,\n"
					+ "      \"guest_type\": \"Loyalty\",\n"
					+ "      \"last_activity_at\": \"2025-05-22T19:07:51Z\",\n"
					+ "      \"last_name\": \"Bsr3985\",\n"
					+ "      \"marketing_email_subscription\": true,\n"
					+ "      \"marketing_pn_subscription\": true,\n"
					+ "      \"phone\": null,\n"
					+ "      \"preferred_locale\": null,\n"
					+ "      \"secondary_email\": null,\n"
					+ "      \"signup_channel\": \"MobileEmail\",\n"
					+ "      \"sms_subscription\": false,\n"
					+ "      \"unsubscribe_reason\": null,\n"
					+ "      \"unsubscribed\": false,\n"
					+ "      \"user_id\": 170115,\n"
					+ "      \"user_status\": \"active\"\n"
					+ "    }\n"
					+ "  }\n"
					+ "}";
			
			return payload ;
			
		}
		
		public String getBrazeTransactionalNotificationGuestConfirmationPayload(String email) {
			
			String payload = "{\n"
					+ "  \"content_id\": \"25b824c4-b5ae-4271-84f3-fdea50e289ab\",\n"
					+ "  \"timestamp\": 1747940750,\n"
					+ "  \"business_id\": 7,\n"
					+ "  \"business_uuid\": \"06fcaf5f-26ee-4fe1-9eee-1ff2c25b5af6\",\n"
					+ "  \"business_slug\": \"fazolis\",\n"
					+ "  \"event_name\": \"transactional_notifications\",\n"
					+ "  \"event_type\": \"confirmation_email\",\n"
					+ "  \"action\": \"create\",\n"
					+ "  \"kafka_offset\": 254027,\n"
					+ "  \"kafka_partition\": 0,\n"
					+ "  \"is_rate_limit\": false,\n"
					+ "  \"payload\": {\n"
					+ "    \"account_balance\": {\n"
					+ "      \"banked_currency\": null,\n"
					+ "      \"current_membership_level_name\": \"Silver Level\",\n"
					+ "      \"last_visit\": null,\n"
					+ "      \"loyalty_points\": 0,\n"
					+ "      \"net_balance\": 2,\n"
					+ "      \"net_debits\": 0,\n"
					+ "      \"pending_points\": 0,\n"
					+ "      \"total_credits\": 2,\n"
					+ "      \"total_debits\": \"0.0\",\n"
					+ "      \"total_lifetime_points\": 2,\n"
					+ "      \"total_point_credits\": 2,\n"
					+ "      \"total_redeemable_visits\": null,\n"
					+ "      \"total_visits\": 0,\n"
					+ "      \"unbanked_points\": null,\n"
					+ "      \"unredeemed_cards\": null,\n"
					+ "      \"user_id\": 170115\n"
					+ "    },\n"
					+ "    \"anniversary\": null,\n"
					+ "    \"avatar_remote_url\": null,\n"
					+ "    \"birthday\": null,\n"
					+ "    \"email\": \""+email+"\",\n"
					+ "    \"email_confirmation_url\": \"https://rohitdoraya.punchh.io/customers/confirmation.iframe?confirmation_token=yjxKoZusReuvZysj4pAs&slug=fazolis\",\n"
					+ "    \"external_source\": \"\",\n"
					+ "    \"external_source_id\": \"170115\",\n"
					+ "    \"first_name\": \"Rohit\",\n"
					+ "    \"gender\": null,\n"
					+ "    \"guest_type\": \"Loyalty\",\n"
					+ "    \"last_activity_at\": \"2025-05-22T19:05:49Z\",\n"
					+ "    \"last_name\": \"Bsr3985\",\n"
					+ "    \"marketing_email_subscription\": true,\n"
					+ "    \"marketing_pn_subscription\": true,\n"
					+ "    \"phone\": null,\n"
					+ "    \"preferred_locale\": null,\n"
					+ "    \"reset_password_url\": null,\n"
					+ "    \"secondary_email\": null,\n"
					+ "    \"signup_channel\": \"MobileEmail\",\n"
					+ "    \"sms_subscription\": false,\n"
					+ "    \"unsubscribe_reason\": null,\n"
					+ "    \"unsubscribed\": false,\n"
					+ "    \"user_id\": 170115,\n"
					+ "    \"user_status\": \"active\"\n"
					+ "  }\n"
					+ "}";
			return payload ;
			
		}
		
}// End of class
