package com.punchh.server.Test;

import java.io.File;
import java.io.FilenameFilter;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.ConcurrentHashMap;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import com.punchh.server.pages.PageObj;
import com.punchh.server.utilities.BrowserUtilities;
import com.punchh.server.utilities.TestListeners;
import com.punchh.server.utilities.Utilities;

//Shashank - This class is used to get the failed test cases from the HTML reports generated by the selenium
@Listeners(TestListeners.class)
public class GetFailureTestCasesFromHTMLReports {

	static Logger logger = LogManager.getLogger(GetFailureTestCasesFromHTMLReports.class);
	public WebDriver driver;
	private Properties prop;
	private PageObj pageObj;
	private String sTCName;
	private String env, run = "ui";
	private static Map<String, String> dataSet;
	public Utilities utils;

	@BeforeMethod(alwaysRun = true)
	public void setUp(Method method) {
		prop = Utilities.loadPropertiesFile("config.properties");
		driver = new BrowserUtilities().launchBrowser();
		sTCName = method.getName();
		pageObj = new PageObj(driver);
		env = pageObj.getEnvDetails().setEnv();
		utils = new Utilities(driver);
		dataSet = new ConcurrentHashMap<>();
		pageObj.readData().ReadDataFromJsonFile(pageObj.readData().getJsonFilePath(run , env), sTCName);
		dataSet = pageObj.readData().readTestData;
		pageObj.readData().ReadDataFromJsonFileForClientSecretKey(
				pageObj.readData().getJsonFilePath(run , env , "Secrets"), dataSet.get("slug"));
		dataSet.putAll(pageObj.readData().readTestData);
		logger.info(sTCName + " ==>" + dataSet);
	}

	// update the folder path where all the html reports are stored
	@Test
	public void readSeleniumHtmlReport() throws InterruptedException {

		List<String> listOfHtmlFiles = new ArrayList<String>();
		List<String> finalFailureCasesList = new ArrayList<String>();

		// Specify the folder path
		// File folder = new File("/Users/punchh_shashank/archive58/RegressionReport");
		File folder = new File("/Users/punchh_hardik/Documents/stableRegressionReport");

		// Filter to get only .html files
		FilenameFilter htmlFilter = (dir, name) -> name.toLowerCase().endsWith(".html");

		// Get the list of .html files
		File[] htmlFiles = folder.listFiles(htmlFilter);

		// Check if the folder is valid and has files
		if (htmlFiles != null && htmlFiles.length > 0) {
			for (File file : htmlFiles) {
				listOfHtmlFiles.add("file://" + file.getAbsolutePath());
				TestListeners.extentTest.get().pass("File Path : file://" + file.getAbsolutePath());
				logger.info("No HTML files found or invalid folder path.");

			}
		} else {
			TestListeners.extentTest.get().fail("No HTML files found or invalid folder path.");
			logger.info("No HTML files found or invalid folder path.");

		}

		Map<String, Integer> htmlReportTestCasesDetailsSize_Map = new HashMap<String, Integer>();
		Map<String, Integer> failureTestCasesMap = new HashMap<String, Integer>();

		for (String file : listOfHtmlFiles) {
			driver.get(file);
			// Path to the Selenium HTML report
			Thread.sleep(4000);
			List<WebElement> listParent_Webelement1 = driver
					.findElements(By.xpath("//li[starts-with(@class,'test-item')][@status='fail']/div/p[1]"));
			System.out.println("Total Passed Test Cases in File  " + file + ": --" + listParent_Webelement1.size());

			TestListeners.extentTest.get()
					.pass("Total Failed Test Cases in File  " + file + ": --" + listParent_Webelement1.size());
			logger.info("Total Failed Test Cases in File  " + file + ": --" + listParent_Webelement1.size());

			htmlReportTestCasesDetailsSize_Map.put(file, listParent_Webelement1.size());
			for (WebElement element : listParent_Webelement1) {
				utils.scrollToElement(driver, element);
				String testCaseName = element.getText();
				if (failureTestCasesMap.containsKey(testCaseName)) {
					failureTestCasesMap.put(testCaseName, failureTestCasesMap.get(testCaseName) + 1);
				} else {
					failureTestCasesMap.put(testCaseName, 1);
				}
			}
		}

		TestListeners.extentTest.get().pass("Total Failed Test Cases in all Files  " + failureTestCasesMap.size());
		logger.info("Total Failed Test Cases in all Files  " + failureTestCasesMap.size());

		TestListeners.extentTest.get().pass(failureTestCasesMap + "");
		logger.info(failureTestCasesMap);

		for (Map.Entry<String, Integer> entry : failureTestCasesMap.entrySet()) {
			if (entry.getValue() > 1)
				finalFailureCasesList.add(entry.getKey());
		}
		TestListeners.extentTest.get()
				.pass("******** Below are the Failed Test Cases " + finalFailureCasesList.size() + " ********");

		for (String str : finalFailureCasesList) {
			TestListeners.extentTest.get().pass(str);
			logger.info(str);

		}

	}

	@AfterMethod(alwaysRun = true)
	public void tearDown() {
		pageObj.utils().clearDataSet(dataSet);
		driver.quit();
		logger.info("Browser closed");
	}

}
