##Environment config

#===========PP Identity============

#baseUrl==https://dashboard.staging.punchh.io/
#baseUrl=https://dashboard.punchh.com/
#baseUrl=https://dashboard.us-west.punchh.com/
#baseUrl=https://business-migration.punchh.io/
#baseUrl=https://api-cloudflare.punchh.com/
#baseUrl=https://api.punchh.com
secret=acf3f27dca79705dc14a1fdc63d84904ab90c76e97cf92326fae0dd04df9f9d4
client=5ed3c669a2c31304b066207507a32156462d9c1d4ed48dd1f2e773d78cbdbcbf

#baseUrl=https://dashboard.us-west.punchh.com/
#secret=82ae6c82fd0042f6058ed749e6344ed081a74cb0d117b4e4d4f38bd7fdfff3de
#client=074d06c17d15fa932c865bf66a6ccc504c823ee7f1d8a25ca8c1ebf61b29406a

###### Common config for all API's
email=superadmin4@example.com
password=password@123
contentType=application/json
firstName=TestFName
lastName=TestLName
zipCode=110015
signUpChannel=MobileEmail
referralCode=khuniSon10
acceptLanguage=en
acceptTimezone=Asia/Kolkata
cacheControl=no-cache
location=308702
birthday=1966-04-04
anniversary=1996-10-03
phone=3344556678
ssoSignupChannel=WebEmail
state=California
updatedBirthday=1966-01-01
updatedAnniversary=1996-01-01
updatedPassword=punchh@12345
zipCode1=12345678910
####API2
userAgent1=MyRewards/2.0/2 (x86_64; iOS 10.3; Scale/2.00)
marketingEmailSubscription=true
privatePolicy=true

#### API config
appBuild=2
appModel=iPhone Simulator
appOs=iOS 10.3
appDeviceId=0GE4218F-59D7-4C46-A4A3-64B3E3B4A5BF-1138437085
userAgent2=Fat Juice Bar/1.2.1/2 (iPhone; iOS 9.0; Scale/2.00)
postManTokenSignUp=83fec726-74bc-475f-acb7-6baf90d32e75
postManTokcenLogin=7c20ba41-02f6-427d-be29-da3b2209ed32
cloudFareToken =LKdb78tetE75M20JzAp82TnL4AWbGY9+OXb7YkKz6bq9gtH0z1/HSoA99t8JYyMh4bFGiXJny2Aii8h2MIoYWz4Kw+9+zPsGrus77xJe0/E=
cloudFareBypass =DGBps9OkTIjtl6Mkz40wypAA/v2SAJUD75kbCy/QkZ2hbi7LiAkzW2Acq/OcSAH13Sbsc8rA9AWI/RyW+utePT4Kw+9+zPsGrus77xJe0/E=

# IRS
irsApiKey=epj08+aSPBisDJzGg1HuHpqEbyQk/+vXs+10hHeVJ7M35ac+GU0oGKWk/OmHKRaS
irsAdminBaseUrl=https://itemrecsysadmin.nonprod.ai.partech.com
irsServiceBaseUrl=https://itemrecsysservice.nonprod.ai.partech.com

#####  POS config
locationKey=5acf3c0b15d61217258c502973f227f1
#locationKey=753f0be2574fa7eeb0c605a4e9bbf2c4
locationKey2=5aea39eb0a4a227089cdcfdb20e8094b
###### Online order Checkin

authenticationToken=WpXF7Kytaj21txqzC7fA
recieptAmount=250
ccLast4=4389

###### POS checkin
authorization=Token token=5acf3c0b15d61217258c502973f227f1
checkinAmount=210

#### AAyushi's script

#password=qwerty1234
#contentType=application/json
##firstName=Aayushi
##lastName=Singh
#birthday=1998-10-07
#anniv=2014-10-27
#favLocation=304987
#marketingEmailSubscription=true
#marketingPnSubscription=true
#externalSourceId=2234561264
#cardNumber=68Temp
#apnToken=1ef397c9 baeba1bf c0f89864 bbe06303 cc6b8d40 3da912b6 928b1db1 3634423f
#gcmToken=APA91bHbjueKkEl0KD7oD16xlNuCFZTDow5aVfSQK5t34JyYOwlfKPik3Z4O5KhAfW9pFhQG_8UexIfcGMVgXX-n8KhLYaOUHsYaMeMasDvA1OR3rS6kZ_A2kZSSu5AXyhimPvWi1CKd
phoneNo=+1-761-754-3915
secondaryEmail=aayushi.singh@punchh.com
##### Azure test data
external_source=azure
external_source_id=884408e1-2918-4cz0-b12d-

######## Zipline test data
zipLineCardNumber=68Temp
ziplineApnToken=1ef397c9 baeba1bf c0f89864 bbe06303 cc6b8d40 3da912b6 928b1db1 3634423f
ziplineGcmToken=APA91bHbjueKkEl0KD7oD16xlNuCFZTDow5aVfSQK5t34JyYOwlfKPik3Z4O5KhAfW9pFhQG_8UexIfcGMVgXX-n8KhLYaOUHsYaMeMasDvA1OR3rS6kZ_A2kZSSu5AXyhimPvWi1CKd

#===========PPCC Service============
pp.ppccServiceBaseUrl = https://mobileapi.staging.punchh.io
encryptionKey = AAAAAAAAAAAAAAAA
## Secret could be any 256 bits long string.
secret = Xa2SWsEXOFbcMO0jVcx+CuHawYGscxDBfOf+FmpUNNvjSoEs3KamvEgLmwVqKN5Ks

#===========Package Service============
pp.packageServiceBaseUrl = https://pospackages.staging.punchh.io/
apiKey = B1UUAVY0Uqxfqhsno2nFV4g0M86SalodgvvSICmKELNtpTQESO9sFobuZ0wXXSvF

#===========Unified Dashboard Service============
pp.unifiedServiceBaseUrl = https://unifieddashboardservice.staging.punchh.io
