
############ Instance config ###############
#----------QA/PP/Dev/local----------------------

#userName=AutoAdmin01@partech.com
userName=superadmin4@example.com
password=Vk5/82gB3lL2EOixpbnGag==

# Email server configuration - Gmail
gmail.store.protocol=imaps
gmail.imaps.host=imap.gmail.com
gmail.imaps.port=993
gmail.imaps.starttls.enable=true

# Gmail credentials
gmail.username=qa.automation.hero
gmail.password=zYKXci0UQI6KGv958WxyOrw8d2msLkRVJ5gbatc9Sgc=

# Twillio credentials - Don't use
twillio.accountSID=IHiZbtd33kzHCUFv6kNGoFK5pdgSQ2iPmS5WCPZQAIaZSubSvQOHA+d7ulUiQDIv
twillio.authToken=tfZGSocDZ2oiY9ESo5Cvu8buURi5GYbOpDdrQz+hnHU+CsPvfsz7Bq7rO+8SXtPx
twillio.fromPhoneNumber=+14253577440

# Auth0 OKTA from email
auth0.fromEmail=auth-no-reply@punchh.com

pp.mobileApiBaseUrl=https://mobileapi.staging.punchh.io
qa.mobileApiBaseUrl=https://mobileapi.qa.punchh.io

# Identity Service Base URL's
pp.guestIdentityBaseUrl=https://preprod-guestidentity.one.partech.com
qa.guestIdentityBaseUrl=https://identity.qa.punchh.io
nipun.guestIdentityBaseUrl=https://identityservice-nipunjain.punchh.io
saurabh.guestIdentityBaseUrl=https://identityservice-saurabhjoshi.punchh.io

# Identity Auth Digest Token's
pp.authDigestToken=8L0g+rcpPaSIapQhf6u5u68sFPXVyYfuc+380i9YBQzrUr4/0n6thVtAMeBxxJrAV4GRe11W6duAlNDK3vvf0xw8QYLxO9U3U1LvMhV31WrjOT7OF0T4g61CN2Vpua7U8Z9oS4ArVmm3wPBSe4QFi0vypPFvSM1rTUi36N8D3NE+CsPvfsz7Bq7rO+8SXtPx
qa.authDigestToken=8L0g+rcpPaSIapQhf6u5u68sFPXVyYfuc+380i9YBQzrUr4/0n6thVtAMeBxxJrAV4GRe11W6duAlNDK3vvf0xw8QYLxO9U3U1LvMhV31WrjOT7OF0T4g61CN2Vpua7U8Z9oS4ArVmm3wPBSe4QFi0vypPFvSM1rTUi36N8D3NE+CsPvfsz7Bq7rO+8SXtPx
nipun.authDigestToken=8L0g+rcpPaSIapQhf6u5u68sFPXVyYfuc+380i9YBQzrUr4/0n6thVtAMeBxxJrAV4GRe11W6duAlNDK3vvf0xw8QYLxO9U3U1LvMhV31WrjOT7OF0T4g61CN2Vpua7U8Z9oS4ArVmm3wPBSe4QFi0vypPFvSM1rTUi36N8D3NE+CsPvfsz7Bq7rO+8SXtPx
saurabh.authDigestToken=8L0g+rcpPaSIapQhf6u5u68sFPXVyYfuc+380i9YBQzrUr4/0n6thVtAMeBxxJrAV4GRe11W6duAlNDK3vvf0xw8QYLxO9U3U1LvMhV31WrjOT7OF0T4g61CN2Vpua7U8Z9oS4ArVmm3wPBSe4QFi0vypPFvSM1rTUi36N8D3NE+CsPvfsz7Bq7rO+8SXtPx

# Encrypted cron digest token
pp.cron_digest_token = lF1pePoTG5Cu+ht1d6pH1E18Av/no6DD/1TSRuKDKw7W8iCuL+MXwEWltvrT6SZ7LhmDIU//wz4fEO1W01yJ4z4Kw+9+zPsGrus77xJe0/E=

# Verifications portal is only deployed on pre-prod
pp.verificationsUrl = https://verify.staging.punchh.io
pp.verificationsPassword=Vk5/82gB3lL2EOixpbnGag==
pp.verificationsUserName=ppyfOZzAcUToJHr8MTsxIP+alqn0QcY96sBpqz70VGM=

# Zephyr config
zephyr.baseUrl=https://api.zephyrscale.smartbear.com/v2
zephyr.projectKey=SQ
zephyr.token=GbfdZm+/THDPxKpEJLUvcPNs8Vz/K1tYQo782s8XMvEF+4p/DVPBN+CYPVRD2zG/NImEjKKttZ72v39ozpp6GyoGTz2JuPAruslEqXtWMir5FPk3Qd1tRUmaU2azx1YKIe1QQzuYlILZUbBtTW2fLI5yIUzMouypko6c8UiD36YAKL6f62PFEYOWO9jB+5mXscNh9S36pM8ojmQqZWb36nzO4szJOVtGGEgbCvFskciVVWhNqINtPvtK3o/x8L7wEymHmhGaaWZ93M5keEbxSG8J4qndymQXU5frU/y6Tdmmg89bk2DRzTHe9KLQYofYFucGBABCLpM07xb85twSTbho0C0OMeM56BUEe5c65lhiLc7Xbx/MPD3hvmTkH0DBI0c/e3ERkDzHDR7l193qlelqHu/aKCjPeE1k5a3BKPtsOHfZXsa2xmaGhYn126dDuRxqn6mZ7fl0V9jXRvvA36qU+WFp9g11Hc/GcKMqPPc6/rwGLFkeRkNyQvC7G062WhfbL+ixiaPQz5tLH6+OGWZ9zsSiK6TPwB0Wfdwz12r0hfZWjGWb88Oo27pBTEteZ03AiFpgwioOdzoY8x6BTg==
executedById=712020:fdbd0330-b700-441e-9eb8-eedf4e5739f8
journeysUrl=https://journeys.punchh.io/
journeysUserName=superadmin1@example.com
journeysPassword=Vk5/82gB3lL2EOixpbnGag==
journeysSlug=nativegrill

## generic config
exisitngUserEmail=naveen@punchh.com

##  iframe config
whiteLabel=whitelabel/
iframeWhitelabel=whitelabel/
firstName=Testfname
lastName=Testlname
iFramePassword=Password@123
iFrameEmailPrefix=autoIframetemp@punchh.com
iFrameEmailPrefix1=updatedemailtemp@abc.com
iFramePassword=password@123
iFrameEmailPrefix=autoiframetemp@punchh.com
iFrameEmailPrefixPunchhPar=autoIframetemp@punchhpar.com
iFrameUpdatedPassword=Super@123
zipCode=110001
zipCode1=112345678900
UpdatedPassword=password@1234

iframeAddress=CyberCity
iframeCity=Gurgaon
iframeState=Haryana
iframePhoneNumber=1234567890
iframeMerchandizeSize=S

## sso config
ssoEmailPrefix=autoSsotemp@punchh.com
joinedViaWebEmail=Joined Us via WebEmail
joinedViaMobile=Joined Us via MobileEmail
joinedViaPOS=Joined Us via POS

#### FTP config
#ftpPath=www/Test/
ftpPath=/
ftpHost=files.000webhost.com
ftpPort=23
ftpUsername=sceptred-questions
ftpPassword=n8trSk9KTzDxXtv
exportFileLoc=
ftpEmail=naveen.mehra@punchh.com
updatedFtpEmail=naveen.mehra+1@punchh.com
#### Barcode checkin 
#location=punchh test
location=Tastea HQ
#location=Test Location
minAmount=15
maxAmount=30
menuItem=9364
itemName=TestMenuItemCola
testBarcode="test_barcodes";

####### Segment configuration
segmentType=Guests Profile Based
guestType=Loyalty guests
segmentDuration=Current Month
segmentDurationAsYear=Current Year
segmentTimezone=Etc/UTC
greenColor=rgba(223, 240, 216, 1)
redColor=rgba(242, 222, 222, 1)
oldUser=khushboo.soni+b50@punchh.com
dummyUrl=https://google.com
segmentAttribute=Age
segmentAttributeAgeValue=60
###### POS checkin
baseConversionRate=3
posLocation= Alhambra - 7

###### FB Signup
fbUsername=akanksha@punchh.com
fbPassword=Punchh@123
deleteReason=delete_general

#### ScheduleFrequency
frequencyImmediate=immediately
exportEmail=naveen.mehra@punchh.com
ftpEndPoint=segment_export_test
segmentExportScheduleType=SegmentExportSchedule
dataExportSchedule=DataDumpSchedule
segmentExportSchedule=SegmentExportSchedule
frequencyOnce=once

## Wifi singup
marketingEmailSubscription=true
joinedViaWifi=Joined Us via Wifi

###
istTimezone=Asia/Kolkata

##
dob=1970-10-20
address=123 ParkAvenue
city= TestCity
stateProvinces=TestState
orignalPoint=10
initialPoint=20
rateOfConversion=3

######

segmentBetaGreen=rgba(49, 155, 141, 1)

###PickupConole
consoleNamePrefix=AGCtemp
locationNamePrefix=AGLAutotemp
phonePrefix=+91temp

#### verifyAllDataExport regression script
ftpEndPointWingStop=TestFTP

### Timezone ###
timezone=(GMT+05:30) New Delhi ( IST )
timezone1=(GMT-07:00) Pacific Time (US & Canada) ( PDT )

### Env URLs #####
pp.baseurl=https://dashboard.staging.punchh.io
qa.baseurl=https://dashboard.qa.punchh.io
dev.baseurl=https://development.punchh.io
load.baseurl=https://dashboard.loadtesting.punchh.io
prod.baseurl=https://dashboard.punchh.com
amit.baseurl=https://amitkumar.punchh.io
vansham.baseurl=https://vanshammishra.punchh.io
nipun.baseurl=https://nipunjain.punchh.io
shivam.baseurl=https://shivammaurya.punchh.io
saurabh.baseurl=https://saurabhjoshi.punchh.io
shashank.baseurl=https://shashanksharma.punchh.io
khushbu.baseurl=https://khushboosoni.punchh.io
rohit.baseurl=https://rohitdoraya.punchh.io
piyush.baseurl=https://piyushkumar.punchh.io
shubham.baseurl=https://shubhamgupta.punchh.io
ajeet.baseurl=https://ajeetsingh.punchh.io
rahulgarg.baseurl=https://rahulgarg.punchh.io
rohit.baseurl=https://rohitdoraya.punchh.io
jeevraj.baseurl=https://jeevrajshekhawat.punchh.io
raja.baseurl=https://rajashekharreddy.punchh.io
nitesh.baseurl=https://niteshshekhawat.punchh.io
akanshajain.baseurl=https://akanshajain.punchh.io
vaibhav.baseurl=https://vaibhavagnihotri.punchh.io
pradeep.baseurl=https://pradeepkumar.punchh.io
hitesh.baseurl=https://hiteshpopli.punchh.io
neha.baseurl=https://nehalodha.punchh.io
divya.baseurl=https://divyachoudhary.punchh.io
unifiedDashboard.baseurl=https://unifieddashboardservice-development.punchh.io

### Download path
downloadPath=/resources/ExportData/

### segment builder clause 
segmentBuilderClauseJson = /resources/builderClauses.json

### Sidekiq Config
sidekiqScheduledJobsLink=/sidekiq/scheduled
sidekiqEnqueuedJobsLink=/sidekiq/queues
expectedSidekiqScheduledLimit=50000
expectedSidekiqEnqueuedLimit=2500


###ashwinisiteadmin
siteadminusername=ashwini.shetty+1803@partech.com
siteadminpassword=Automation@123

### Google Test Account
testAccountEmail=testautomation050@gmail.com
testAccountPwd=gC307ZRWfib/PUwylGWwNj4Kw+9+zPsGrus77xJe0/E=
googlePaySaveUrl=https://pay.google.com
googleWalletUrl=https://wallet.google.com

### Sidekiq urls
qa.sidekiqUrl=AG24np99Cyp9CrXa7eLpV9/qxV+4Kk2rikhMkDKyd9abA7PEUsNcW5tZ3l4iPhZi
pp.sidekiqUrl=ptQGoahJUA8UHhXUXKzdCOL1b7OskiG6Cd+zQSSMZXMqp18/iX7uP6e6ssiLaH1RCUdcqc/0bX0Q8M69kXmDFA==

# Unified Dashboard Service Base URL's
pp.unifiedDashboardBaseUrl=https://unifieddashboard.staging.punchh.io/
dev.unifiedDashboardBaseUrl=https://unifieddashboard-development.punchh.io/

# Offer Service Base URL's
shashank.offerservice.baseurl=https://offerservice-shashanksharma.punchh.io