## DB config
## This file contains the database connection details for different environments

#===========Nipun DB Details============
nipun.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
nipun.DBName=nipunjain
nipun.UserName=1BokmPCYJFVd/YS2iZTH3A==
nipun.Password=3AJ631tQbYWKHLl9mwBQxg==
nipun.Port=3306
nipun.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= PP DB Details for remote connection <worked on jenkins>======
pp.remote.Host=primary-punchh-pre-prod.punchh-internal.net
pp.remote.DBName=punchh_production
pp.remote.UserName=UMcHcDyppihm8tT3Vrckvg==
pp.remote.Password=TYulmBazB7byzbTHG4LFiw==
pp.remote.verificationsDBName = punchh_verifications
pp.remote.receiptsDBName = receipt_store_production
pp.remote.Port=3306
pp.remote.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= PP DB Details for local connection<worked on local machine using teleport ======
pp.local.Host=localhost
pp.local.DBName=punchh_production
#User for PP local DB no need
#pp.local.UserName=
#pp.local.Password=
pp.local.verificationsDBName =punchh_verifications
pp.local.receiptsDBName =receipt_store_production
pp.local.Port=3306
pp.local.Params=useSSL=false&allowPublicKeyRetrieval=true

# change hashed UserName in case executing locally
pp.local.guestIdentity.Host=localhost
pp.local.guestIdentity.DBName=guest_identity_pre_prod
pp.local.guestIdentity.UserName=TS6ncL+bGMtqEMlKXZnT2R2NGmAk09J96Qwz9ExPg2Q=
#hardik local
#pp.local.guestIdentity.UserName=Cfx348jGMAq9z+I0l/FQ2R2NGmAk09J96Qwz9ExPg2Q=
pp.local.guestIdentity.Password=
pp.local.guestIdentity.Port=3309
pp.local.guestIdentity.Params=useSSL=false&allowPublicKeyRetrieval=true

pp.remote.guestIdentity.Host=pre-prod-guestidentity.cluster-c73iwq08jhzr.us-west-2.rds.amazonaws.com
pp.remote.guestIdentity.DBName=guest_identity_pre_prod
pp.remote.guestIdentity.UserName=ENL6sqBudrxpRi2mFgfkHA==
pp.remote.guestIdentity.Password=rRj+nB7YFli0iqd8DKlpdA==
pp.remote.guestIdentity.Port=3306
pp.remote.guestIdentity.Params=useSSL=false&allowPublicKeyRetrieval=true


pp.remote.MongoUsername=88GlqTErSBl0fDmUoavrLQ==
pp.remote.MongoPassword=4MxueBTF5KX6oWflMPsFu0ESdhLqTwio6e7jkTJPW+Q=
pp.remote.MongoHOST=pre-prod-docdb-tf.cluster-c73iwq08jhzr.us-west-2.docdb.amazonaws.com
pp.remote.EventDBName=event_framework_production
pp.remote.InboundDBName=inbound_stream
pp.remote.CommonDBName=punchh_production
pp.remote.MongoPort=27017

pp.local.MongoUsername=88GlqTErSBl0fDmUoavrLQ==
pp.local.MongoPassword=4MxueBTF5KX6oWflMPsFu0ESdhLqTwio6e7jkTJPW+Q=
pp.local.MongoHOST=localhost
pp.local.EventDBName=event_framework_production
pp.local.InboundDBName=inbound_stream
pp.local.CommonDBName=punchh_production
pp.local.MongoPort=27017


#========= QA DB Details======
qa.Host=punchh-qa.cqxf8abfzoua.us-east-1.rds.amazonaws.com
qa.DBName=punchh_production
qa.UserName=L8Mu7xPZ4eRDv8w9P5Zp7XPPmgE3kQnk3OohEN+72BI=
qa.Password=EHhKdt+T3t8IKjf84bWE1D4Kw+9+zPsGrus77xJe0/E=
qa.Port=3306
qa.Params=useSSL=false&allowPublicKeyRetrieval=true

#========
subscriptionCreditDataExport = select rc.id as reward_credit_id, rc.user_id, rc.rewarded_by_id as user_subscription_id, us.subscription_plan_id, sp.name as subscription_plan_name, rc.rewarded_for_id as subscription_discount_id,\n"
				+ "rc.type as reward_credit_type, rc.banked_reward_value, rc.created_at as reward_credit_created_date_time_utc, rc.reward_reason as reward_credit_reason, rc.expiring_at as reward_credit_expiration_date_time_utc\n"
				+ "from reward_credits rc join user_subscriptions us on us.business_id = rc.business_id and us.user_id = rc.user_id and us.id = rc.rewarded_by_id\n"
				+ "join subscription_plans sp on us.business_id = sp.business_id and us.subscription_plan_id = sp.id where rc.rewarded_by_type = 'UserSubscription' and rc.type = 'SubscriptionCredit' and rc.rewarded_for_type = 'SubscriptionDiscount'\n"
				+ "and rc.business_id =
				
#========= Divya DB Details======
divya.local.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
divya.local.DBName=divya
divya.local.UserName=MJIfJ3FLAssJAlwXejO/9Q==
divya.local.Password=6I5CI4264SNOEKNJsgVmRw==
divya.local.Port=3306
divya.local.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= Khushbu DB Details======
khushbu.local.Host=localhost
khushbu.local.DBName=khushboosoni
khushbu.local.UserName=wsH4+2SoZ0JriDXw/nBzBjy8fSmw6RcsJW8T16JNYp0=
khushbu.local.Password=
khushbu.local.Port=3307
khushbu.local.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= Jeevraj DB Details======
jeevraj.local.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
jeevraj.local.Port=3306/jeevrajshekhawat?useSSL=false&allowPublicKeyRetrieval=true
jeevraj.local.UserName=RGhXSMNysTqq23kMSQEOGg==
jeevraj.local.Password=u7wcX+vOABzsnXOVWAXyaA==

#========= Shivam DB Details ======
#shivam.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
#shivam.DBName=shivammaurya
#shivam.UserName=yBumCWFqVUms0HhMQSJkew==
#shivam.Password=V1Axq3HedfxzLX7NrasVOw==
#shivam.Port=3306
#shivam.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= Shivam Maurya DB Details with teleport ======
shivam.local.Host=localhost
shivam.local.DBName=shivammaurya
shivam.local.UserName=khvjcYJbcias2L6uLDie6zy8fSmw6RcsJW8T16JNYp0=
shivam.Password=
shivam.local.Port=3307
shivam.Params=

#========= Vansham DB Details======
vansham.local.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
vansham.local.DBName=vanshammishra
vansham.local.UserName=OmpB0j8uhFOQfd7wgH4Xmg==
vansham.local.Password=rwY+1kj/J3CakZsoNj297A==
vansham.local.Port=3306
vansham.local.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= Vaibhav Agnihotri DB Details ======
vaibhav.local.Host=localhost
vaibhav.local.DBName=vaibhavagnihotri
vaibhav.local.UserName=
vaibhav.local.Password=
vaibhav.local.Port=3307
vaibhav.local.Params=

#========= saurabh DB Details======
saurabh.local.Host=localhost
saurabh.local.DBName=saurabhjoshi
saurabh.local.UserName=YpYTXK8jqe5HqisFzMZBRTy8fSmw6RcsJW8T16JNYp0=
saurabh.local.Password=
saurabh.local.Port=50434
saurabh.local.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= Shashank Sharma DB Details======
shashank.remote.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
shashank.remote.DBName=shashanksharma
shashank.remote.UserName=e81wLSs1cCXRayP8/6CA7g==
shashank.remote.Password=5IOWEk1DhVN1bNB8bLAoRQ==
shashank.remote.Port=3306
shashank.remote.Params=useSSL=false&allowPublicKeyRetrieval=true
shashank.remote.receiptsDBName =shashanksharma




#========= Shashank Sharma DB Details with teleport======
shashank.local.Host=localhost
shashank.local.DBName=shashanksharma
shashank.local.UserName=TS6ncL+bGMtqEMlKXZnT2R2NGmAk09J96Qwz9ExPg2Q=
shashank.local.Password=
shashank.local.Port=3307
shashank.local.Params=
shashank.local.receiptsDBName =shashanksharma

#========= Rohit Doraya DB Details======

rohit.local.Host=localhost
rohit.local.DBName=rohitdoraya
rohit.local.UserName=LGJuX4vFK/EPd3V0j6gfTw==
rohit.local.Password=gacLRCt8ITiGEafnqN4d4A==
rohit.local.Port=3306
rohit.local.Params=useSSL=false&allowPublicKeyRetrieval=true

rohit.local.MongoUsername=LGJuX4vFK/EPd3V0j6gfTw==
rohit.local.MongoPassword=gacLRCt8ITiGEafnqN4d4A==
rohit.local.MongoHOST=localhost
rohit.local.EventDBName=rohitdoraya
rohit.local.InboundDBName=rohitdoraya
rohit.local.CommonDBName=rohitdoraya
rohit.local.MongoPort=27017

#========= perf DB Details======
perf.username  =  LqScJ1knKJqEbBD6FYMyHQ==
perf.password  =  pqBHX9tKcF43uLbmBzZL+g==

#========= dev DB Details======
#dev.Host=pre-prod-mysql8.cj8hufhw12ic.us-east-1.rds.amazonaws.com
#dev.DBName=punchh_production
#dev.UserName=ENL6sqBudrxpRi2mFgfkHA==
#dev.Password=VD7ZL/k+kFlvqoKOToSnHVAu1l9izHi3uNe97SBkqy4=
#dev.Port=3306
#dev.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= dev teleport======
dev.local.Host=localhost
dev.local.DBName=punchh_production
dev.local.UserName=
dev.local.Password=
dev.local.Port=51252
dev.local.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= Rahul Garg DB Details with teleport======
rahulgarg.local.Host=localhost
rahulgarg.local.DBName=rahulgarg
rahulgarg.local.UserName=hZ+M/uExEDltB8mOZwkqIP+alqn0QcY96sBpqz70VGM=
rahulgarg.local.Password=
rahulgarg.local.Port=3307
rahulgarg.local.Params=

#===========Raja DB Details============
raja.local.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
raja.local.DBName=rajashekharreddy
raja.UserName=WU5lPrCJdldHH3XehJOMGT4Kw+9+zPsGrus77xJe0/E=
raja.local.Password=QVFcQJFUElV37f1RngYoKw==
raja.local.Port=3306
raja.local.Params=useSSL=false&allowPublicKeyRetrieval=true


#========= Nitesh Shekhawat DB Details======
nitesh.local.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
nitesh.local.Port=3306
nitesh.local.Params=useSSL=false&allowPublicKeyRetrieval=true
nitesh.local.UserName=XFsHbxKK6n5RJeXVy7S1xg==
nitesh.local.DBName=niteshshekhawat
nitesh.local.Password=MNGlVAHjZLq6si3vvAiV+g==


#========= Teleport Akansha DB Details======
akanshajain.local.Host=localhost
akanshajain.local.DBName=akanshajain
akanshajain.local.UserName=bdXhAiy3OhszuWbkX03aXgEYfbVre/j7xZjxkCTI3zw=
akanshajain.local.Port=3310


#========= Shubham DB Details======
#shubham.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
#shubham.DBName=shubhamgupta
#shubham.UserName=l1QWCeNEoNrPRH+AfH2A3w==
#shubham.Password=q/NSpEnRRPsnuSodMx83tw==
#shubham.Port=3306
#shubham.Params=useSSL=false&allowPublicKeyRetrieval=true

#============Teleport Shubham DB Details===========
shubham.local.Host=localhost
shubham.local.DBName=shubhamgupta
shubham.local.UserName=
shubham.Password=
shubham.local.verificationsDBName =punchh_verifications
shubham.local.receiptsDBName =receipt_store_production
shubham.local.Port=50238


#============Teleport Pradeep DB Details===========
pradeep.local.Host=localhost
pradeep.local.DBName=pradeepkumar
pradeep.local.UserName=
pradeep.local.Password=
pradeep.local.verificationsDBName =punchh_verifications
pradeep.local.receiptsDBName =receipt_store_production
pradeep.local.Port=3306
pradeep.local.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= jeevrajshekhawat DB Details======
jeevraj.local.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
jeevraj.local.DBName=jeevrajshekhawat
jeevraj.local.UserName=YiLiNSD7v/nB4N+dbSv2VD4Kw+9+zPsGrus77xJe0/E=
jeevraj.local.Password=togrhUToj5TNiD6QXD30LQ==
jeevraj.local.Port=3306
jeevraj.local.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= hiteshpopli DB Details======
hitesh.local.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
hitesh.local.DBName=hiteshpopli
hitesh.local.UserName= cSaps9+L29KC+eK0Vdrm2Q==
hitesh.local.Password=fpV5FrAUEf3AjJVIqxisWg==
hitesh.local.Port=3306
hitesh.local.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= piyushkumar DB Details======
piyush.local.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
piyush.local.DBName=piyushkumar
piyush.local.UserName= zMlWjhSfThRCLrnzDkJdDw==
piyush.local.Password=uIXB/3ikgk69EbHU4u6i4g==
piyush.local.Port=3306
piyush.local.Params=useSSL=false&allowPublicKeyRetrieval=true

#============Neha DB Details===========

neha.local.Host=engineering.cj8hufhw12ic.us-east-1.rds.amazonaws.com
neha.local.DBName=nehalodha
neha.local.UserName=9nkcRywQX8tqoNWBDzZzWA==
neha.local.Password=LaMNjR0kaFrfokyHn1iMgw==
neha.local.Port=3306
neha.local.Params=useSSL=false&allowPublicKeyRetrieval=true



#========= DEV DB Details for local connection<worked on local machine using teleport ======
dev.local.Host=localhost
dev.local.DBName=punchh_production
#User for PP local DB no need
#pp.local.UserName=
#pp.local.Password=
dev.local.verificationsDBName =punchh_verifications
dev.local.receiptsDBName =receipt_store_production
dev.local.Port=3305
dev.local.Params=useSSL=false&allowPublicKeyRetrieval=true

#========= Nitesh Shekhawat DB Details with teleport======

nitesh.local.Host=localhost
nitesh.local.DBName=niteshshekhawat
nitesh.local.UserName=TS6ncL+bGMtqEMlKXZnT2R2NGmAk09J96Qwz9ExPg2Q=
nitesh.local.Port=3306

